'use client';

import Link from 'next/link';
import { useTranslation } from '@/components/locale-provider';

const copy = {
  en: { title: 'Independent Worker Disclaimer', body: ['Workers using EverittOS may be independent workers of the organization that assigned the work. They are not employees of EverittOS merely because they use this software. EverittOS provides scheduling, communication, job documentation, and payment-status tools.', 'The hiring organization and worker are responsible for compensation, classification, taxes, insurance, licensing, working conditions, and legal compliance. EverittOS does not guarantee work assignments, payment, employment status, or the accuracy of information entered by an organization.', 'Calendar events are provided for convenience. Confirm appointment details in EverittOS because external calendar updates may be delayed or affected by provider settings.'], general: 'General disclaimer', terms: 'Terms of Service', privacy: 'Privacy Policy', portal: 'Worker portal' },
  es: { title: 'Aviso para trabajadores independientes', body: ['Los trabajadores que usan EverittOS pueden ser trabajadores independientes de la organización que asignó el trabajo. No son empleados de EverittOS simplemente por usar este software. EverittOS ofrece herramientas de programación, comunicación, documentación de trabajos y estado de pagos.', 'La organización contratante y el trabajador son responsables de compensación, clasificación, impuestos, seguros, licencias, condiciones de trabajo y cumplimiento legal. EverittOS no garantiza asignaciones, pagos, condición laboral ni la exactitud de la información ingresada por una organización.', 'Los eventos de calendario se ofrecen por comodidad. Confirma los detalles de la cita en EverittOS porque las actualizaciones de calendarios externos pueden retrasarse o depender de la configuración del proveedor.'], general: 'Aviso general', terms: 'Términos de servicio', privacy: 'Política de privacidad', portal: 'Portal del trabajador' },
  vi: { title: 'Tuyên bố dành cho nhân viên độc lập', body: ['Nhân viên sử dụng EverittOS có thể là nhân viên độc lập của tổ chức giao việc. Họ không trở thành nhân viên của EverittOS chỉ vì sử dụng phần mềm này. EverittOS cung cấp công cụ lập lịch, liên lạc, tài liệu công việc và trạng thái thanh toán.', 'Tổ chức thuê và nhân viên chịu trách nhiệm về thù lao, phân loại lao động, thuế, bảo hiểm, giấy phép, điều kiện làm việc và tuân thủ pháp luật. EverittOS không bảo đảm việc được giao, thanh toán, tình trạng việc làm hoặc độ chính xác của thông tin do tổ chức nhập.', 'Sự kiện lịch chỉ nhằm mục đích thuận tiện. Hãy xác nhận chi tiết cuộc hẹn trong EverittOS vì cập nhật từ lịch bên ngoài có thể bị chậm hoặc chịu ảnh hưởng bởi cài đặt của nhà cung cấp.'], general: 'Tuyên bố chung', terms: 'Điều khoản dịch vụ', privacy: 'Chính sách quyền riêng tư', portal: 'Cổng nhân viên' }
} as const;

export default function ContractorDisclaimerPage() {
  const { locale } = useTranslation();
  const c = copy[locale] || copy.en;
  return <main className="section"><div className="container" style={{ maxWidth: 720 }}><h1>{c.title}</h1>{c.body.map((p) => <p key={p}>{p}</p>)}<nav className="button-row" style={{ marginTop: 24, flexWrap: 'wrap', gap: 8 }}><Link className="btn" href="/disclaimer">{c.general}</Link><Link className="btn" href="/terms">{c.terms}</Link><Link className="btn" href="/privacy">{c.privacy}</Link><Link className="btn" href="/portal/contractor">{c.portal}</Link></nav></div></main>;
}
