'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ExportMenu } from '@/components/export-menu';
import { RoleHomeCard } from '@/components/role-home-card';
import { useTranslation } from '@/components/locale-provider';
import { contractorJobDetailPath } from '@/lib/contractor-job-access';
import { getExportCopy } from '@/lib/i18n/export-copy';
import { readWorkerJobCache, saveWorkerJobCache } from '@/lib/worker-job-cache';
import { supabase } from '@/lib/supabase';
import { performClientLogout } from '@/lib/client-logout';

type JobRow = { id:string; title:string|null; customerName:string|null; address:string|null; status:string|null; startDate:string|null; dueDate:string|null; scheduledStart:string|null; completedAt:string|null; payAmount:number|null; paymentStatus:'paid'|'pending'|'unpaid'|null; };
type PortalTotals = { assigned:number; upcoming:number; completed:number; total:number; paid:number; owed:number; };
type PortalDashboardResponse = { notLinked?:boolean; workerName?:string; jobs?:JobRow[]; totals?:PortalTotals; error?:string; };
type AuthResult = { data:{user:{id:string;email?:string|null}|null}; error:{message?:string}|null };
type LoadState='loading'|'ready'|'error';
const LOAD_TIMEOUT_MS=10000;
const EMPTY_TOTALS:PortalTotals={assigned:0,upcoming:0,completed:0,total:0,paid:0,owed:0};
const copy={
 en:{contractor:'Worker',dashboard:'Your work',goodMorning:'Good morning',goodAfternoon:'Good afternoon',goodEvening:'Good evening',upcomingHeadline:'upcoming jobs',upcomingHeadlineOne:'upcoming job',jobs:'Jobs',earnings:'Earnings',settings:'Settings',more:'More',signOut:'Sign out',signingOut:'Signing out...',loadingTitle:'Loading your work...',loadingBody:'This should take only a few seconds.',errorTitle:'Your work could not load',errorSafe:'No jobs or payments were changed.',tryAgain:'Try again',offline:'Connection unavailable. Showing the last saved job list from this device.',job:'Job',customer:'Customer',noJobs:'No assigned jobs yet.',paid:'paid',stillOwedLower:'still owed',earningsBody:'Earnings are based on payment records linked to your worker profile.',yourPay:'Your pay',payNotRecorded:'Pay details pending',nextUp:'Next job',openJob:'Open job',loadFailed:'Your work could not load.',sessionTimeout:'Your session took too long to load.',jobsTimeout:'Assigned jobs took too long to load.',notLinked:'Your login is not linked to a worker profile yet. Ask the company owner to link your email to your worker record.',status:{scheduled:'scheduled',completed:'completed',complete:'complete',done:'done',finished:'finished',closed:'closed',cancelled:'cancelled',canceled:'canceled'}},
 es:{contractor:'Trabajador',dashboard:'Tu trabajo',goodMorning:'Buenos días',goodAfternoon:'Buenas tardes',goodEvening:'Buenas noches',upcomingHeadline:'trabajos próximos',upcomingHeadlineOne:'trabajo próximo',jobs:'Trabajos',earnings:'Ganancias',settings:'Configuración',more:'Más',signOut:'Cerrar sesión',signingOut:'Cerrando sesión...',loadingTitle:'Cargando tu trabajo...',loadingBody:'Esto solo debería tardar unos segundos.',errorTitle:'No se pudo cargar tu trabajo',errorSafe:'No se cambiaron trabajos ni pagos.',tryAgain:'Intentar de nuevo',offline:'No hay conexión. Se muestra la última lista de trabajos guardada en este dispositivo.',job:'Trabajo',customer:'Cliente',noJobs:'Aún no hay trabajos asignados.',paid:'pagado',stillOwedLower:'pendiente',earningsBody:'Las ganancias se basan en los registros de pago vinculados a tu perfil.',yourPay:'Tu pago',payNotRecorded:'Detalles de pago pendientes',nextUp:'Próximo trabajo',openJob:'Abrir trabajo',loadFailed:'No se pudo cargar tu trabajo.',sessionTimeout:'Tu sesión tardó demasiado en cargar.',jobsTimeout:'Los trabajos tardaron demasiado en cargar.',notLinked:'Tu inicio de sesión aún no está vinculado a un perfil de trabajador. Pide al propietario que vincule tu correo electrónico.',status:{scheduled:'programado',completed:'terminado',complete:'terminado',done:'terminado',finished:'terminado',closed:'cerrado',cancelled:'cancelado',canceled:'cancelado'}},
 vi:{contractor:'Nhân viên',dashboard:'Công việc của bạn',goodMorning:'Chào buổi sáng',goodAfternoon:'Chào buổi chiều',goodEvening:'Chào buổi tối',upcomingHeadline:'công việc sắp tới',upcomingHeadlineOne:'công việc sắp tới',jobs:'Công việc',earnings:'Thu nhập',settings:'Cài đặt',more:'Thêm',signOut:'Đăng xuất',signingOut:'Đang đăng xuất...',loadingTitle:'Đang tải công việc...',loadingBody:'Quá trình này chỉ mất vài giây.',errorTitle:'Không thể tải công việc',errorSafe:'Không có công việc hoặc khoản thanh toán nào bị thay đổi.',tryAgain:'Thử lại',offline:'Không có kết nối. Đang hiển thị danh sách công việc được lưu gần nhất.',job:'Công việc',customer:'Khách hàng',noJobs:'Chưa có công việc được giao.',paid:'đã trả',stillOwedLower:'còn phải trả',earningsBody:'Thu nhập dựa trên hồ sơ thanh toán liên kết với hồ sơ nhân viên.',yourPay:'Tiền công của bạn',payNotRecorded:'Chi tiết tiền công đang chờ',nextUp:'Công việc tiếp theo',openJob:'Mở công việc',loadFailed:'Không thể tải công việc.',sessionTimeout:'Phiên đăng nhập mất quá lâu để tải.',jobsTimeout:'Công việc mất quá lâu để tải.',notLinked:'Tài khoản của bạn chưa được liên kết với hồ sơ nhân viên. Hãy nhờ chủ công ty liên kết email của bạn.',status:{scheduled:'đã lên lịch',completed:'đã xong',complete:'đã xong',done:'đã xong',finished:'đã xong',closed:'đã đóng',cancelled:'đã hủy',canceled:'đã hủy'}}
} as const;
function withTimeout<T>(promise:PromiseLike<T>,message:string):Promise<T>{return new Promise<T>((resolve,reject)=>{const timer=window.setTimeout(()=>reject(new Error(message)),LOAD_TIMEOUT_MS);Promise.resolve(promise).then(v=>{window.clearTimeout(timer);resolve(v)},e=>{window.clearTimeout(timer);reject(e)})})}
function money(value:number,locale:string){return new Intl.NumberFormat(locale,{style:'currency',currency:'USD'}).format(value)}
function normalizedStatus(value:string|null){return String(value||'scheduled').trim().toLowerCase().replace(/\s+/g,'_')}
export default function ContractorPortalPage(){
 const router=useRouter();const{locale}=useTranslation();const c=copy[locale]||copy.en;const exportCopy=getExportCopy(locale);const localeCode=locale==='vi'?'vi-VN':locale==='es'?'es-US':'en-US';
 const[state,setState]=useState<LoadState>('loading');const[error,setError]=useState('');const[offlineNotice,setOfflineNotice]=useState('');const[,setWorkerName]=useState('');const[jobs,setJobs]=useState<JobRow[]>([]);const[totals,setTotals]=useState<PortalTotals>(EMPTY_TOTALS);const[signingOut,setSigningOut]=useState(false);const[exportError,setExportError]=useState('');
 const jobDate=useCallback((job:JobRow)=>{const value=job.scheduledStart||job.startDate||job.dueDate||job.completedAt;if(!value)return'';const date=new Date(value.includes('T')?value:`${value}T12:00:00`);return Number.isNaN(date.getTime())?'':date.toLocaleString(localeCode,{month:'short',day:'numeric',...(value.includes('T')?{hour:'numeric',minute:'2-digit'}:{})})},[localeCode]);
 const statusLabel=useCallback((value:string|null)=>{const key=normalizedStatus(value) as keyof typeof c.status;return c.status[key]||normalizedStatus(value).replaceAll('_',' ')},[c.status]);
 const load=useCallback(async()=>{setState('loading');setError('');setOfflineNotice('');let userId='';try{const auth=(await withTimeout(supabase.auth.getUser(),c.sessionTimeout)) as AuthResult;const user=auth.data.user;if(auth.error||!user){router.replace('/login?next=%2Fportal%2Fcontractor');return}userId=user.id;const response=(await withTimeout(fetch('/api/portal/contractor/jobs',{cache:'no-store'}),c.jobsTimeout)) as Response;if(response.status===401){router.replace('/login?next=%2Fportal%2Fcontractor');return}const payload=(await response.json().catch(()=>({}))) as PortalDashboardResponse;if(!response.ok)throw new Error(payload.error||c.loadFailed);const nextName=payload.workerName||user.email||c.contractor;const nextJobs=payload.jobs||[];const nextTotals=payload.totals||EMPTY_TOTALS;setWorkerName(nextName);if(payload.notLinked){setJobs([]);setTotals(EMPTY_TOTALS);setError(c.notLinked);setState('error');return}setJobs(nextJobs);setTotals(nextTotals);saveWorkerJobCache(user.id,{workerName:nextName,jobs:nextJobs,totals:nextTotals});setState('ready')}catch(cause){const cached=userId?readWorkerJobCache(userId):null;if(cached){setWorkerName(cached.workerName);setJobs(cached.jobs);setTotals(cached.totals);setOfflineNotice(c.offline);setState('ready');return}setError(cause instanceof Error?cause.message:c.loadFailed);setState('error')}},[c,router]);
 useEffect(()=>{void load()},[load]);
 const sortedJobs=useMemo(()=>[...jobs].sort((a,b)=>String(a.scheduledStart||a.startDate||'').localeCompare(String(b.scheduledStart||b.startDate||''))),[jobs]);const headline=c.dashboard;const subhead=state==='ready'?`${totals.upcoming} ${totals.upcoming===1?c.upcomingHeadlineOne:c.upcomingHeadline}`:'';const nextJob=sortedJobs.find(job=>!['completed','complete','done','finished','closed','cancelled','canceled'].includes(normalizedStatus(job.status)));
 async function signOut(){if(signingOut)return;setSigningOut(true);try{await performClientLogout();window.location.assign('/login')}catch{setSigningOut(false);router.replace('/login')}}
 return <div className="contractor-dashboard role-dashboard-minimal">
  <RoleHomeCard className="contractor-portal-hero" title={headline} subtitle={subhead}>{state==='ready'&&nextJob?<div className="contractor-next-job eo-role-home-next"><div className="contractor-next-copy eo-upcoming-content"><span className="contractor-next-label">{c.nextUp}</span><strong className="contractor-next-title">{nextJob.title||c.job}</strong>{jobDate(nextJob)?<span className="contractor-next-meta">{jobDate(nextJob)}</span>:null}{nextJob.customerName||nextJob.address?<span className="contractor-next-meta">{[nextJob.customerName,nextJob.address].filter(Boolean).join(' · ')}</span>:null}</div><Link className="btn btn-primary contractor-next-action eo-upcoming-actions" href={contractorJobDetailPath(nextJob.id)}>{c.openJob}</Link></div>:null}</RoleHomeCard>
  {exportError?<p className="auth-message auth-message-error">{exportError}</p>:null}
  {state==='loading'?<section className="card" aria-live="polite"><h3 style={{marginTop:0}}>{c.loadingTitle}</h3><p className="muted">{c.loadingBody}</p></section>:null}
  {state==='error'?<section className="card" role="alert"><h3 style={{marginTop:0}}>{c.errorTitle}</h3><p>{error}</p><p className="muted">{c.errorSafe}</p><button type="button" className="btn btn-primary" onClick={()=>void load()}>{c.tryAgain}</button></section>:null}
  {state==='ready'?<><section id="jobs" className="card contractor-content-card"><h2 style={{marginTop:0}}>{c.jobs}</h2>{sortedJobs.length?<div className="job-visits-list">{sortedJobs.map(job=><article key={job.id} className="list-row portal-job-row"><Link href={contractorJobDetailPath(job.id)} className="worker-job-link" aria-label={`${c.openJob}: ${job.title||c.job}`}><div><strong>{job.title||c.job}</strong>{jobDate(job)?<p className="muted portal-job-date" style={{margin:'5px 0 0'}}>{jobDate(job)}</p>:null}<p style={{margin:'5px 0 0'}}>{job.customerName||c.customer}{job.address?` · ${job.address}`:''}</p></div><div className="portal-job-finance"><span className={`status-badge portal-status-${normalizedStatus(job.status)}`}>{statusLabel(job.status)}</span>{job.payAmount==null?<span className="portal-finance-empty">{c.payNotRecorded}</span>:<strong className="portal-finance-amount">{c.yourPay}: {money(job.payAmount,localeCode)}</strong>}</div></Link></article>)}</div>:<p className="muted">{c.noJobs}</p>}</section><details className="card contractor-content-card contractor-more"><summary><strong>{c.more}</strong></summary><section id="earnings"><h3>{c.earnings}</h3><p><strong>{money(totals.paid,localeCode)}</strong> {c.paid} · <strong>{money(totals.owed,localeCode)}</strong> {c.stillOwedLower}</p><p className="muted">{c.earningsBody}</p></section><div className="button-row"><Link className="btn" href="/portal/contractor/settings">{c.settings}</Link><ExportMenu endpoint="/api/exports/portal/contractor/jobs" locale={locale} labels={{export:exportCopy.downloadMyJobs,csv:exportCopy.downloadMyJobsCsv,pdf:exportCopy.downloadMyJobsPdf}} disabled={Boolean(offlineNotice)} onError={message=>setExportError(message||exportCopy.exportFailed)} onSuccess={()=>setExportError('')}/><button type="button" className="btn contractor-signout" disabled={signingOut} onClick={()=>void signOut()}>{signingOut?c.signingOut:c.signOut}</button></div></details></>:null}

 </div>
}
