'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ExportMenu } from '@/components/export-menu';
import { useTranslation } from '@/components/locale-provider';
import { PortalClientNav } from '@/components/portal/portal-client-nav';
import { CLIENT_SETTINGS_PATH } from '@/lib/client-portal';
import { getExportCopy } from '@/lib/i18n/export-copy';
import { clientPortalJobsPath, CLIENT_PORTAL_HOME } from '@/lib/portal-access';
import { isClientRole, normalizeRole } from '@/lib/roles';
import { localToday, wallClockFromTimestamp } from '@/lib/schedule-times';
import { supabase } from '@/lib/supabase';

type ClientJob = { id:string; title:string; status:string|null; customerName:string|null; address:string|null; scheduledStart:string|null; scheduledEnd:string|null; startDate:string|null; dueDate:string|null; completedAt:string|null; createdAt:string|null; jobTotal:number|null; paid:number; balanceDue:number|null; };
type TimeRange = 'today'|'week'|'month'|'year'|'all';
const copy={en:{today:'Today',week:'This week',month:'This month',year:'This year',all:'All',timePeriod:'Time period',nextVisit:'Next visit',upcoming:'Upcoming visits',completed:'Past visits',noUpcoming:'No appointments yet.',noCompleted:'No completed appointments yet.',balanceDue:'Balance due',status:'Status',dateNotSet:'Schedule pending',viewVisit:'View visit',statuses:{scheduled:'scheduled',completed:'completed',complete:'completed',finished:'completed',done:'completed',cancelled:'cancelled',canceled:'cancelled'}},es:{today:'Hoy',week:'Esta semana',month:'Este mes',year:'Este año',all:'Todo',timePeriod:'Período',nextVisit:'Próxima visita',upcoming:'Próximas visitas',completed:'Visitas anteriores',noUpcoming:'Aún no hay citas.',noCompleted:'Aún no hay citas terminadas.',balanceDue:'Saldo pendiente',status:'Estado',dateNotSet:'Horario pendiente',viewVisit:'Ver visita',statuses:{scheduled:'programado',completed:'terminado',complete:'terminado',finished:'terminado',done:'terminado',cancelled:'cancelado',canceled:'cancelado'}},vi:{today:'Hôm nay',week:'Tuần này',month:'Tháng này',year:'Năm nay',all:'Tất cả',timePeriod:'Khoảng thời gian',nextVisit:'Lịch hẹn tiếp theo',upcoming:'Lịch hẹn sắp tới',completed:'Lịch hẹn trước',noUpcoming:'Chưa có lịch hẹn.',noCompleted:'Chưa có lịch hẹn đã hoàn thành.',balanceDue:'Số còn lại',status:'Trạng thái',dateNotSet:'Lịch đang chờ',viewVisit:'Xem lịch hẹn',statuses:{scheduled:'đã lên lịch',completed:'đã xong',complete:'đã xong',finished:'đã xong',done:'đã xong',cancelled:'đã hủy',canceled:'đã hủy'}}} as const;
function cityState(address:string|null){if(!address)return'';const parts=address.split(',').map(p=>p.trim()).filter(Boolean);return parts.length>=2?parts.slice(-2).join(', '):address}
function operationalDate(job:ClientJob){return wallClockFromTimestamp(job.scheduledStart)?.date||job.startDate?.slice(0,10)||job.dueDate?.slice(0,10)||job.createdAt?.slice(0,10)||''}
function normalizedStatus(job:ClientJob){return String(job.status||'').trim().toLowerCase().replace(/\s+/g,'_')}
function isFinished(job:ClientJob){return['completed','complete','finished','done'].includes(normalizedStatus(job))}
function isCancelled(job:ClientJob){return['cancelled','canceled'].includes(normalizedStatus(job))}
function jobDate(job:ClientJob,locale:string){const value=operationalDate(job);if(!value)return'';return new Date(`${value.slice(0,10)}T12:00:00`).toLocaleDateString(locale,{weekday:'long',month:'long',day:'numeric'})}
function jobTime(job:ClientJob,locale:string){const start=wallClockFromTimestamp(job.scheduledStart);const end=wallClockFromTimestamp(job.scheduledEnd);if(!start?.time)return'';const format=(time:string)=>new Date(`2000-01-01T${time}:00`).toLocaleTimeString(locale,{hour:'numeric',minute:'2-digit'});return end?.time?`${format(start.time)} – ${format(end.time)}`:format(start.time)}
function formatMoney(value:number|null,locale:string){if(value==null||!Number.isFinite(Number(value)))return'';return new Intl.NumberFormat(locale,{style:'currency',currency:'USD'}).format(Number(value))}
function rangeBounds(range:TimeRange){const now=new Date();const start=new Date(now.getFullYear(),now.getMonth(),now.getDate());const end=new Date(start);if(range==='today')end.setDate(end.getDate()+1);if(range==='week')end.setDate(end.getDate()+7);if(range==='month')end.setMonth(end.getMonth()+1);if(range==='year')end.setFullYear(end.getFullYear()+1);return{start:start.toISOString().slice(0,10),end:end.toISOString().slice(0,10)}}
export default function ClientPortalJobsPage(){const router=useRouter();const{t,locale}=useTranslation();const c=copy[locale]||copy.en;const exportCopy=getExportCopy(locale);const localeCode=locale==='vi'?'vi-VN':locale==='es'?'es-US':'en-US';const[jobs,setJobs]=useState<ClientJob[]>([]);const[range,setRange]=useState<TimeRange>('month');const[loading,setLoading]=useState(true);const[message,setMessage]=useState('');const[empty,setEmpty]=useState(false);const[exportError,setExportError]=useState('');
useEffect(()=>{async function load(){setEmpty(false);const{data:{user}}=await supabase.auth.getUser();if(!user){router.push(`/login?next=${encodeURIComponent(clientPortalJobsPath())}`);return}const{data:profileRow}=await supabase.from('profiles').select('role').eq('id',user.id).maybeSingle();if(!isClientRole(normalizeRole(profileRow?.role))){router.replace(CLIENT_PORTAL_HOME);return}const response=await fetch('/api/portal/client/jobs',{cache:'no-store'});if(response.status===401){router.push(`/login?next=${encodeURIComponent(clientPortalJobsPath())}`);return}const payload=(await response.json().catch(()=>({}))) as{jobs?:ClientJob[];error?:string};if(!response.ok){setMessage(payload.error||t('portal.client.jobLoadError'));setLoading(false);return}const jobRows=payload.jobs||[];if(jobRows.length===0){setMessage('');setEmpty(true);setLoading(false);return}setJobs(jobRows);setMessage('');setEmpty(false);setLoading(false)}void load()},[router,t]);
const nextVisit=useMemo(()=>{const today=localToday();return jobs.filter(job=>{const date=operationalDate(job);return !isFinished(job)&&!isCancelled(job)&&Boolean(date&&date>=today)}).sort((a,b)=>operationalDate(a).localeCompare(operationalDate(b)))[0]||null},[jobs]);
const visibleJobs=useMemo(()=>{if(range==='all')return jobs;const{start,end}=rangeBounds(range);return jobs.filter(job=>{const date=operationalDate(job);return date&&date>=start&&date<end})},[jobs,range]);
const groupedJobs=useMemo(()=>{const today=localToday();const current:ClientJob[]=[];const history:ClientJob[]=[];for(const job of visibleJobs){const date=operationalDate(job);if(isFinished(job)||isCancelled(job)||(date&&date<today))history.push(job);else current.push(job)}current.sort((a,b)=>operationalDate(a).localeCompare(operationalDate(b)));history.sort((a,b)=>operationalDate(b).localeCompare(operationalDate(a)));return{current,history}},[visibleJobs]);
function statusLabel(job:ClientJob){const key=normalizedStatus(job) as keyof typeof c.statuses;return c.statuses[key]||normalizedStatus(job).replace(/_/g,' ')}
function renderJobCard(job:ClientJob){const date=jobDate(job,localeCode);const time=jobTime(job,localeCode);const location=cityState(job.address);const balance=Number(job.balanceDue||0);return <Link key={job.id} href={clientPortalJobsPath(job.id)} className="client-job-card simplified-job-card" aria-label={job.title}><div className="client-job-card-main"><h3>{job.title}</h3>{date||time?<p className="client-job-secondary">{[date,time].filter(Boolean).join(' · ')}</p>:null}{location?<p className="client-job-secondary">{location}</p>:null}</div><div className="client-job-card-meta">{job.status?<span className={`status-badge portal-status-${normalizedStatus(job)}`}>{statusLabel(job)}</span>:null}{balance>0?<p className="portal-finance-line"><span>{c.balanceDue} <strong className="portal-finance-amount">{formatMoney(balance,localeCode)}</strong></span></p>:null}</div></Link>}
function renderSection(id:string,title:string,rows:ClientJob[],emptyText:string,open=false){return <details id={id} className="card portal-dashboard-section" open={open}><summary><h2>{title}</h2><span>{rows.length}</span></summary>{rows.length===0?<p className="muted">{emptyText}</p>:<div className="client-job-card-list">{rows.map(renderJobCard)}</div>}</details>}
if(loading)return <div className="client-portal-jobs"><div className="card" role="status">{t('portal.client.loadingSharedJobs')}</div></div>;
return <div className="client-portal-jobs role-dashboard-minimal"><PortalClientNav active="appointments" overviewHref={CLIENT_PORTAL_HOME} appointmentsHref={clientPortalJobsPath()} accountHref={CLIENT_SETTINGS_PATH}/>{exportError?<p className="auth-message auth-message-error">{exportError}</p>:null}{empty?<div className="card client-empty-state" role="status"><p>{c.noUpcoming}</p></div>:message?<div className="card" role="alert"><p>{message}</p></div>:<>{nextVisit?<section className="card client-next-visit"><p className="eyebrow">{c.nextVisit}</p><h1>{nextVisit.title}</h1><p>{[jobDate(nextVisit,localeCode),jobTime(nextVisit,localeCode)].filter(Boolean).join(' · ')}</p>{nextVisit.address?<p className="muted">{nextVisit.address}</p>:null}{Number(nextVisit.balanceDue||0)>0?<p><strong>{c.balanceDue}: {formatMoney(nextVisit.balanceDue,localeCode)}</strong></p>:null}<Link className="btn btn-primary" href={clientPortalJobsPath(nextVisit.id)}>{c.viewVisit}</Link></section>:null}<div className="role-dashboard-topbar client-visit-tools"><label className="client-period-select"><span className="sr-only">{c.timePeriod}</span><select value={range} onChange={event=>setRange(event.target.value as TimeRange)} aria-label={c.timePeriod}><option value="today">{c.today}</option><option value="week">{c.week}</option><option value="month">{c.month}</option><option value="year">{c.year}</option><option value="all">{c.all}</option></select></label><ExportMenu endpoint="/api/exports/portal/client/jobs" query={{range}} locale={locale} labels={{export:exportCopy.downloadMyJobs,csv:exportCopy.downloadMyJobsCsv,pdf:exportCopy.downloadMyJobsPdf}} disabled={loading||Boolean(message)||empty} onError={err=>setExportError(err||exportCopy.exportFailed)} onSuccess={()=>setExportError('')}/></div>{renderSection('current-jobs',c.upcoming,groupedJobs.current,c.noUpcoming,true)}{renderSection('history',c.completed,groupedJobs.history,c.noCompleted)}</>}</div>}
