'use client';
import Link from 'next/link';
import { useCallback,useEffect,useState } from 'react';
import { useRouter } from 'next/navigation';
import { AppShell } from '@/components/app-shell';
import { LocalizedEmptyState } from '@/components/localized-empty-state';
import { PageHeader } from '@/components/page-header';
import { useTranslation } from '@/components/locale-provider';
import { useAppFeedback } from '@/components/feedback/use-app-feedback';
import { useAsyncAction } from '@/hooks/use-async-action';
import { FEEDBACK } from '@/lib/feedback-labels';
import { fetchOrganizationContext } from '@/lib/organization';
import { normalizePlan,type EverittosPlan } from '@/lib/everittos-plans';
import { isManagerRole,normalizeRole,type UserRole } from '@/lib/roles';
import { supabase } from '@/lib/supabase';
import type { EverittForm,FormType } from '@/lib/os-types';
const copy={
 en:{title:'Forms',subtitle:'Create and manage forms for leads, estimates, bookings, and customer intake.',newForm:'New form',name:'Name',example:'Example: Free quote',type:'Type',create:'Create',loading:'Loading...',active:'Active',off:'Off',open:'Open',view:'View public form',more:'More',remove:'Remove',confirm:'Remove',loadError:'Unable to load forms',types:{contact:'Contact',estimate:'Estimate request',lead_capture:'Lead form',client_intake:'Customer intake',booking:'Booking request',custom:'Custom'}},
 es:{title:'Formularios',subtitle:'Crea y administra formularios para prospectos, estimados, reservas y clientes.',newForm:'Nuevo formulario',name:'Nombre',example:'Ejemplo: Cotización gratis',type:'Tipo',create:'Crear',loading:'Cargando...',active:'Activo',off:'Desactivado',open:'Abrir',view:'Ver formulario público',more:'Más',remove:'Eliminar',confirm:'Eliminar',loadError:'No se pudieron cargar los formularios',types:{contact:'Contacto',estimate:'Solicitud de estimado',lead_capture:'Formulario de prospecto',client_intake:'Registro de cliente',booking:'Solicitud de reserva',custom:'Personalizado'}},
 vi:{title:'Biểu mẫu',subtitle:'Tạo và quản lý biểu mẫu cho khách tiềm năng, báo giá, đặt lịch và khách hàng.',newForm:'Biểu mẫu mới',name:'Tên',example:'Ví dụ: Báo giá miễn phí',type:'Loại',create:'Tạo',loading:'Đang tải...',active:'Đang bật',off:'Đã tắt',open:'Mở',view:'Xem biểu mẫu công khai',more:'Thêm',remove:'Xóa',confirm:'Xóa',loadError:'Không thể tải biểu mẫu',types:{contact:'Liên hệ',estimate:'Yêu cầu báo giá',lead_capture:'Biểu mẫu khách tiềm năng',client_intake:'Thông tin khách hàng',booking:'Yêu cầu đặt lịch',custom:'Tùy chỉnh'}}
} as const;
const VALUES:FormType[]=['contact','estimate','lead_capture','client_intake','booking','custom'];
export default function FormsPage(){const router=useRouter();const feedback=useAppFeedback();const{busy,runResponse,buttonLabel}=useAsyncAction();const{locale}=useTranslation();const c=copy[locale];const[plan,setPlan]=useState<EverittosPlan>('free');const[role,setRole]=useState<UserRole>('owner');const[forms,setForms]=useState<EverittForm[]>([]);const[name,setName]=useState('');const[formType,setFormType]=useState<FormType>('contact');const[loading,setLoading]=useState(true);const[canManage,setCanManage]=useState(false);
 const load=useCallback(async()=>{setLoading(true);const{data:{user}}=await supabase.auth.getUser();if(!user){router.push('/login');return;}const{data:profile}=await supabase.from('profiles').select('plan, role').eq('id',user.id).maybeSingle();const org=await fetchOrganizationContext(user.id);const userRole=normalizeRole(org?.role||profile?.role);setPlan(normalizePlan(profile?.plan));setRole(userRole);setCanManage(isManagerRole(userRole));const res=await fetch('/api/forms');const json=await res.json();setLoading(false);if(!res.ok){feedback.error(json.error||c.loadError);return;}setForms(json.forms||[]);},[feedback,router,c.loadError]);useEffect(()=>{void load();},[load]);
 async function createForm(){if(!name.trim()||busy)return;const res=await runResponse(()=>fetch('/api/forms',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name.trim(),form_type:formType})}),'created');if(!res)return;setName('');void load();}
 async function deleteForm(id:string,formName:string){if(!window.confirm(`${c.confirm} ${formName}?`))return;const res=await runResponse(()=>fetch(`/api/forms/${id}`,{method:'DELETE'}),'deleted');if(res)void load();}
 return <AppShell plan={plan} role={role}><PageHeader title={c.title} subtitle={c.subtitle}/>{canManage?<details className="card" style={{marginBottom:18}}><summary><strong>{c.newForm}</strong></summary><div className="form" style={{marginTop:16}}><label>{c.name}</label><input className="input" placeholder={c.example} value={name} onChange={e=>setName(e.target.value)}/><label>{c.type}</label><select className="input" value={formType} onChange={e=>setFormType(e.target.value as FormType)}>{VALUES.map(value=><option key={value} value={value}>{c.types[value]}</option>)}</select><button type="button" className="btn btn-primary" disabled={busy||!name.trim()} onClick={()=>void createForm()}>{buttonLabel(c.create,FEEDBACK.loading)}</button></div></details>:null}
 {loading?<div className="card"><p className="loading-state">{c.loading}</p></div>:null}{!loading&&forms.length===0?<LocalizedEmptyState emptyKey="forms" compact/>:null}{!loading&&forms.length>0?<div style={{display:'grid',gap:14}}>{forms.map(form=><article key={form.id} className="card"><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'flex-start'}}><div><h3 style={{marginBottom:6}}>{form.name}</h3><p className="muted" style={{marginBottom:0}}>{c.types[form.form_type]||form.form_type.replaceAll('_',' ')}</p></div><span className={`status-pill ${form.active?'status-pill-success':'status-pill-muted'}`}>{form.active?c.active:c.off}</span></div><div className="button-row" style={{marginTop:14,flexWrap:'wrap'}}><Link className="btn btn-primary" href={`/forms/${form.id}`}>{c.open}</Link><a className="btn" href={`/f/${form.slug}`} target="_blank" rel="noreferrer">{c.view}</a></div>{canManage?<details style={{marginTop:14}}><summary><strong>{c.more}</strong></summary><div className="button-row" style={{marginTop:12}}><button type="button" className="btn btn-danger" disabled={busy} onClick={()=>void deleteForm(form.id,form.name)}>{c.remove}</button></div></details>:null}</article>)}</div>:null}</AppShell>;
}
