'use client';

import { useEffect, useRef } from 'react';
import { useTranslation } from '@/components/locale-provider';

const ES: Record<string, string> = {
  'Loading portal...': 'Cargando portal...',
  'Loading your client portal...': 'Cargando tu portal de cliente...',
  'Loading your shared jobs...': 'Cargando tus trabajos compartidos...',
  'Loading shared job...': 'Cargando trabajo compartido...',
  'Loading account settings…': 'Cargando configuración de la cuenta…',
  'Loading…': 'Cargando…',
  'Client portal': 'Portal del cliente',
  'Contractor portal': 'Portal del contratista',
  'Your service': 'Tu servicio',
  'Shared jobs': 'Trabajos compartidos',
  'Only jobs shared with you are listed here.': 'Aquí solo aparecen los trabajos compartidos contigo.',
  'View appointment details, reports, and photos shared with you.': 'Consulta los detalles de la cita, los informes y las fotos compartidas contigo.',
  'Overview': 'Resumen',
  'Appointments': 'Citas',
  'Schedule': 'Horario',
  'Reports & photos': 'Informes y fotos',
  'Reports & Photos': 'Informes y fotos',
  'Invoices': 'Facturas',
  'Account': 'Cuenta',
  'Sign out': 'Cerrar sesión',
  'Signing out…': 'Cerrando sesión…',
  'Upcoming Appointment': 'Próxima cita',
  'No upcoming appointments.': 'No hay citas próximas.',
  'Job Status': 'Estado del trabajo',
  'No jobs shared yet.': 'Aún no hay trabajos compartidos.',
  'Invoices & Payments': 'Facturas y pagos',
  'No invoices yet.': 'Aún no hay facturas.',
  'No shared reports yet.': 'Aún no hay informes compartidos.',
  'View reports & photos': 'Ver informes y fotos',
  'View details': 'Ver detalles',
  'Your profile': 'Tu perfil',
  'Name:': 'Nombre:',
  'Email:': 'Correo electrónico:',
  'Phone:': 'Teléfono:',
  'Business:': 'Empresa:',
  'Not set': 'Sin definir',
  'Linked customer records': 'Registros de clientes vinculados',
  'No email': 'Sin correo electrónico',
  'No phone': 'Sin teléfono',
  'Edit account settings': 'Editar configuración de la cuenta',
  'Customer portal disclaimer': 'Aviso del portal del cliente',
  'Shared reports': 'Informes compartidos',
  'No reports have been shared with you.': 'No se han compartido informes contigo.',
  'Appointment report': 'Informe de la cita',
  'Open report': 'Abrir informe',
  'Photos': 'Fotos',
  'No appointments yet.': 'Aún no hay citas.',
  'Invoices and payments': 'Facturas y pagos',
  'You do not have any open invoices.': 'No tienes facturas pendientes.',
  'Amount pending': 'Importe pendiente',
  'No shared jobs yet': 'Aún no hay trabajos compartidos',
  'There are currently no shared jobs for your account. When a business shares a job with you, it will appear here.': 'Actualmente no hay trabajos compartidos con tu cuenta. Cuando una empresa comparta un trabajo contigo, aparecerá aquí.',
  'Open job': 'Abrir trabajo',
  'Hide photos': 'Ocultar fotos',
  'View photos': 'Ver fotos',
  'No reports have been shared with you for this job.': 'No se han compartido informes contigo para este trabajo.',
  'Activity timeline': 'Cronología de actividad',
  'Job update': 'Actualización del trabajo',
  'Privacy Policy': 'Política de privacidad',
  'Terms of Service': 'Términos del servicio',
  'Customer Portal Disclaimer': 'Aviso del portal del cliente',
  'Account settings': 'Configuración de la cuenta',
  'Back to shared jobs': 'Volver a trabajos compartidos',
  'Appointment': 'Cita',
  'Status:': 'Estado:',
  'Date:': 'Fecha:',
  'Reports': 'Informes',
  'No reports have been shared for this job yet.': 'Todavía no se han compartido informes para este trabajo.',
  'Open': 'Abrir',
  'View': 'Ver',
  'Date not set': 'Fecha sin definir',
  'Due:': 'Vence:',
  'Due': 'Vence',
  'Today': 'Hoy',
  "Today's Jobs": 'Trabajos de hoy',
  'Nothing scheduled for today.': 'No hay nada programado para hoy.',
  'Upcoming Jobs': 'Próximos trabajos',
  'No upcoming jobs.': 'No hay próximos trabajos.',
  'Past Jobs': 'Trabajos anteriores',
  'completed': 'completados',
  'No completed jobs yet.': 'Aún no hay trabajos completados.',
  'Earnings': 'Ganancias',
  'Paid': 'Pagado',
  'Owed': 'Pendiente',
  'No payment history yet.': 'Aún no hay historial de pagos.',
  'Job': 'Trabajo',
  'Customer': 'Cliente',
  'Work date': 'Fecha de trabajo',
  'Earned': 'Ganado',
  'Outstanding': 'Pendiente',
  'Status': 'Estado',
  'Paid date': 'Fecha de pago',
  'Notifications': 'Notificaciones',
  'Preferences': 'Preferencias',
  'No notifications yet.': 'Aún no hay notificaciones.',
  'Update': 'Actualización',
  'unread': 'sin leer',
  'Legal': 'Legal',
  'Policies that apply to contractor portal access.': 'Políticas aplicables al acceso al portal del contratista.',
  'Contractor Disclaimer': 'Aviso del contratista',
  'Could not load everything': 'No se pudo cargar todo',
  'Try again': 'Intentar de nuevo',
  'Start job': 'Iniciar trabajo',
  'Mark complete': 'Marcar como completado',
  'Open details': 'Abrir detalles',
  'Job photos': 'Fotos del trabajo',
  'Pay:': 'Pago:',
  'Payment:': 'Pago:',
  'Not set': 'Sin definir',
  'Profile': 'Perfil',
  'Update the contact details used for job and account notifications.': 'Actualiza los datos de contacto utilizados para las notificaciones de trabajos y cuenta.',
  'First name': 'Nombre',
  'Last name': 'Apellido',
  'Display name': 'Nombre para mostrar',
  'New email': 'Nuevo correo electrónico',
  'New password': 'Nueva contraseña',
  'Leave blank to keep current email': 'Déjalo en blanco para conservar el correo actual',
  'Leave blank to keep current password': 'Déjalo en blanco para conservar la contraseña actual',
  'Save account': 'Guardar cuenta',
  'Account settings saved.': 'Configuración de la cuenta guardada.',
  'Choose which contractor updates you want by email.': 'Elige qué actualizaciones del contratista deseas recibir por correo electrónico.',
  'Choose which appointment and invoice updates you want by email.': 'Elige qué actualizaciones de citas y facturas deseas recibir por correo electrónico.',
  'Email notifications': 'Notificaciones por correo electrónico',
  'Job and payment updates': 'Actualizaciones de trabajos y pagos',
  'Appointment and invoice updates': 'Actualizaciones de citas y facturas',
  'Product updates': 'Actualizaciones del producto',
  'Language': 'Idioma',
  'Review the policies that apply to your portal access.': 'Revisa las políticas aplicables a tu acceso al portal.',
  'Calendar': 'Calendario'
};

const VI: Record<string, string> = {
  'Loading portal...': 'Đang tải cổng thông tin...',
  'Loading your client portal...': 'Đang tải cổng thông tin khách hàng...',
  'Loading your shared jobs...': 'Đang tải các công việc được chia sẻ...',
  'Loading shared job...': 'Đang tải công việc được chia sẻ...',
  'Loading account settings…': 'Đang tải cài đặt tài khoản…',
  'Loading…': 'Đang tải…',
  'Client portal': 'Cổng thông tin khách hàng',
  'Contractor portal': 'Cổng thông tin nhà thầu',
  'Your service': 'Dịch vụ của bạn',
  'Shared jobs': 'Công việc được chia sẻ',
  'Only jobs shared with you are listed here.': 'Chỉ những công việc được chia sẻ với bạn mới xuất hiện tại đây.',
  'View appointment details, reports, and photos shared with you.': 'Xem chi tiết lịch hẹn, báo cáo và hình ảnh được chia sẻ với bạn.',
  'Overview': 'Tổng quan',
  'Appointments': 'Lịch hẹn',
  'Schedule': 'Lịch trình',
  'Reports & photos': 'Báo cáo và hình ảnh',
  'Reports & Photos': 'Báo cáo và hình ảnh',
  'Invoices': 'Hóa đơn',
  'Account': 'Tài khoản',
  'Sign out': 'Đăng xuất',
  'Signing out…': 'Đang đăng xuất…',
  'Upcoming Appointment': 'Lịch hẹn sắp tới',
  'No upcoming appointments.': 'Không có lịch hẹn sắp tới.',
  'Job Status': 'Trạng thái công việc',
  'No jobs shared yet.': 'Chưa có công việc được chia sẻ.',
  'Invoices & Payments': 'Hóa đơn và thanh toán',
  'No invoices yet.': 'Chưa có hóa đơn.',
  'No shared reports yet.': 'Chưa có báo cáo được chia sẻ.',
  'View reports & photos': 'Xem báo cáo và hình ảnh',
  'View details': 'Xem chi tiết',
  'Your profile': 'Hồ sơ của bạn',
  'Name:': 'Tên:',
  'Email:': 'Email:',
  'Phone:': 'Điện thoại:',
  'Business:': 'Doanh nghiệp:',
  'Not set': 'Chưa đặt',
  'Linked customer records': 'Hồ sơ khách hàng được liên kết',
  'No email': 'Không có email',
  'No phone': 'Không có số điện thoại',
  'Edit account settings': 'Chỉnh sửa cài đặt tài khoản',
  'Customer portal disclaimer': 'Tuyên bố miễn trừ trách nhiệm của cổng khách hàng',
  'Shared reports': 'Báo cáo được chia sẻ',
  'No reports have been shared with you.': 'Chưa có báo cáo nào được chia sẻ với bạn.',
  'Appointment report': 'Báo cáo lịch hẹn',
  'Open report': 'Mở báo cáo',
  'Photos': 'Hình ảnh',
  'No appointments yet.': 'Chưa có lịch hẹn.',
  'Invoices and payments': 'Hóa đơn và thanh toán',
  'You do not have any open invoices.': 'Bạn không có hóa đơn nào đang mở.',
  'Amount pending': 'Số tiền đang chờ',
  'No shared jobs yet': 'Chưa có công việc được chia sẻ',
  'There are currently no shared jobs for your account. When a business shares a job with you, it will appear here.': 'Hiện chưa có công việc nào được chia sẻ với tài khoản của bạn. Khi một doanh nghiệp chia sẻ công việc với bạn, công việc đó sẽ xuất hiện tại đây.',
  'Open job': 'Mở công việc',
  'Hide photos': 'Ẩn hình ảnh',
  'View photos': 'Xem hình ảnh',
  'No reports have been shared with you for this job.': 'Chưa có báo cáo nào được chia sẻ với bạn cho công việc này.',
  'Activity timeline': 'Dòng thời gian hoạt động',
  'Job update': 'Cập nhật công việc',
  'Privacy Policy': 'Chính sách quyền riêng tư',
  'Terms of Service': 'Điều khoản dịch vụ',
  'Customer Portal Disclaimer': 'Tuyên bố miễn trừ trách nhiệm của cổng khách hàng',
  'Account settings': 'Cài đặt tài khoản',
  'Back to shared jobs': 'Quay lại công việc được chia sẻ',
  'Appointment': 'Lịch hẹn',
  'Status:': 'Trạng thái:',
  'Date:': 'Ngày:',
  'Reports': 'Báo cáo',
  'No reports have been shared for this job yet.': 'Chưa có báo cáo nào được chia sẻ cho công việc này.',
  'Open': 'Mở',
  'View': 'Xem',
  'Date not set': 'Chưa đặt ngày',
  'Due:': 'Hạn:',
  'Due': 'Hạn',
  'Today': 'Hôm nay',
  "Today's Jobs": 'Công việc hôm nay',
  'Nothing scheduled for today.': 'Hôm nay không có công việc nào được lên lịch.',
  'Upcoming Jobs': 'Công việc sắp tới',
  'No upcoming jobs.': 'Không có công việc sắp tới.',
  'Past Jobs': 'Công việc trước đây',
  'completed': 'đã hoàn thành',
  'No completed jobs yet.': 'Chưa có công việc hoàn thành.',
  'Earnings': 'Thu nhập',
  'Paid': 'Đã trả',
  'Owed': 'Còn nợ',
  'No payment history yet.': 'Chưa có lịch sử thanh toán.',
  'Job': 'Công việc',
  'Customer': 'Khách hàng',
  'Work date': 'Ngày làm việc',
  'Earned': 'Đã kiếm',
  'Outstanding': 'Còn lại',
  'Status': 'Trạng thái',
  'Paid date': 'Ngày trả',
  'Notifications': 'Thông báo',
  'Preferences': 'Tùy chọn',
  'No notifications yet.': 'Chưa có thông báo.',
  'Update': 'Cập nhật',
  'unread': 'chưa đọc',
  'Legal': 'Pháp lý',
  'Policies that apply to contractor portal access.': 'Các chính sách áp dụng cho quyền truy cập cổng thông tin nhà thầu.',
  'Contractor Disclaimer': 'Tuyên bố miễn trừ trách nhiệm của nhà thầu',
  'Could not load everything': 'Không thể tải đầy đủ dữ liệu',
  'Try again': 'Thử lại',
  'Start job': 'Bắt đầu công việc',
  'Mark complete': 'Đánh dấu hoàn thành',
  'Open details': 'Mở chi tiết',
  'Job photos': 'Hình ảnh công việc',
  'Pay:': 'Tiền công:',
  'Payment:': 'Thanh toán:',
  'Not set': 'Chưa đặt',
  'Profile': 'Hồ sơ',
  'Update the contact details used for job and account notifications.': 'Cập nhật thông tin liên hệ dùng cho thông báo công việc và tài khoản.',
  'First name': 'Tên',
  'Last name': 'Họ',
  'Display name': 'Tên hiển thị',
  'New email': 'Email mới',
  'New password': 'Mật khẩu mới',
  'Leave blank to keep current email': 'Để trống để giữ email hiện tại',
  'Leave blank to keep current password': 'Để trống để giữ mật khẩu hiện tại',
  'Save account': 'Lưu tài khoản',
  'Account settings saved.': 'Đã lưu cài đặt tài khoản.',
  'Choose which contractor updates you want by email.': 'Chọn các cập nhật dành cho nhà thầu mà bạn muốn nhận qua email.',
  'Choose which appointment and invoice updates you want by email.': 'Chọn các cập nhật về lịch hẹn và hóa đơn mà bạn muốn nhận qua email.',
  'Email notifications': 'Thông báo qua email',
  'Job and payment updates': 'Cập nhật công việc và thanh toán',
  'Appointment and invoice updates': 'Cập nhật lịch hẹn và hóa đơn',
  'Product updates': 'Cập nhật sản phẩm',
  'Language': 'Ngôn ngữ',
  'Review the policies that apply to your portal access.': 'Xem các chính sách áp dụng cho quyền truy cập cổng thông tin của bạn.',
  'Calendar': 'Lịch'
};

function translateText(value: string, dictionary: Record<string, string>) {
  let result = value;
  for (const [source, target] of Object.entries(dictionary).sort((a, b) => b[0].length - a[0].length)) {
    if (result.includes(source)) result = result.split(source).join(target);
  }
  return result;
}

export function PortalViewTranslator({ children }: { children: React.ReactNode }) {
  const { locale } = useTranslation();
  const rootRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const dictionary = locale === 'es' ? ES : locale === 'vi' ? VI : null;
    const translate = () => {
      const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
      let node = walker.nextNode();
      while (node) {
        const parent = node.parentElement;
        if (parent && !['SCRIPT', 'STYLE', 'TEXTAREA', 'INPUT', 'OPTION'].includes(parent.tagName)) {
          const original = node.textContent || '';
          const english = node.parentElement?.dataset.portalEnglish || original;
          if (node.parentElement && !node.parentElement.dataset.portalEnglish && original.trim()) {
            node.parentElement.dataset.portalEnglish = original;
          }
          const next = dictionary ? translateText(english, dictionary) : english;
          if (node.textContent !== next) node.textContent = next;
        }
        node = walker.nextNode();
      }
    };

    translate();
    const observer = new MutationObserver(translate);
    observer.observe(root, { childList: true, subtree: true, characterData: true });
    return () => observer.disconnect();
  }, [locale]);

  return <div ref={rootRef}>{children}</div>;
}
