import './globals.css';
import type { Metadata, Viewport } from 'next';
import { cookies } from 'next/headers';
import { Manrope } from 'next/font/google';
import { CookieConsentBanner } from '@/components/cookie-consent-banner';
import { ToastProvider } from '@/components/feedback/toast-provider';
import { LocaleProvider } from '@/components/locale-provider';
import { LocaleSync } from '@/components/locale-sync';
import { SiteChrome, SkipToMain } from '@/components/site-chrome';
import { AnalyticsGate } from '@/components/analytics-gate';
import { ActivityHeartbeat } from '@/components/activity-heartbeat';
import { SessionGuard } from '@/components/session-guard';
import { WorkspaceBootstrap } from '@/components/workspace-bootstrap';
import { WorkspacePlanProvider } from '@/components/workspace-plan-provider';
import { AppConnectivityBanner } from '@/components/app-connectivity-banner';
import { NetworkStatusBanner } from '@/components/network-status-banner';
import { NativeAppProvider } from '@/components/native-app-provider';
import { NativePinLock } from '@/components/native-pin-lock';
import { MobileDocumentFlags } from '@/components/mobile-document-flags';
import { MobileBottomNav } from '@/components/mobile-bottom-nav';
import { PwaRegistration } from '@/components/pwa-registration';
import { PwaUpdatePrompt } from '@/components/pwa-update-prompt';
import { SuppressVercelToolbar } from '@/components/suppress-vercel-toolbar';
import { SupabaseRuntimeConfig } from '@/components/supabase-runtime-config';
import { ContractorStaticSections } from '@/components/portal/contractor-static-sections';
import { JobFinanceWordingAndCustomerRate } from '@/components/job-finance-wording-and-customer-rate';
import { CreateFormCancelControls } from '@/components/create-form-cancel-controls';
import { ContractorJobPayVisibility } from '@/components/contractor-job-pay-visibility';
import { ExpensesListEnhancer } from '@/components/expenses-list-enhancer';
import { AskEverittQuickClear } from '@/components/ask-everitt-quick-clear';
import { vercelDeploymentEnv } from '@/lib/deployment-env';
import { LOCALE_COOKIE_NAME, normalizeLocale } from '@/lib/i18n/config';
import './everitt-theme.css'; import './everitt-app-polish.css'; import './everitt-editorial-fixes.css'; import './typography.css'; import './nav.css'; import './outbound.css'; import './feedback-toast.css'; import './app-readability-pass.css'; import './customer-ready-polish.css'; import './dashboard.css'; import './job-mobile-fixes.css'; import './payment-receipt-modal-fix.css'; import './job-visit-layout-override.css'; import './form-alignment-fixes.css'; import './jobs-visual-polish.css'; import './mobile-safe-areas.css'; import './receipt.css'; import './mobile-usability-fixes.css'; import './everitt-modern-refresh.css'; import './text-contrast.css'; import './contractor-portal.css'; import './native-tablet-release-polish.css'; import './everitt-visual-system.css'; import './final-layout-guard.css'; import './jobs-visual-final.css'; import './jobs-actions-spacing-fix.css'; import './team-customer-consistency.css'; import './button-consistency.css'; import './final-app-polish.css'; import './final-overlay-polish.css'; import './final-compact-controls-polish.css'; import './final-language-layout-polish.css'; import './sidebar-plan-card-polish.css'; import './navigation-visibility-guard.css'; import './role-dashboard-v1.css'; import './jobs-owner-minimal.css'; import './portal-role-consistency.css'; import './mobile-overflow-final-fix.css'; import './contractor-outlook-label-fix.css'; import './dashboard-responsive-fit.css'; import './job-form-spacing-final.css'; import './cross-role-alignment-final.css'; import './settings-card-spacing-final.css'; import './notification-settings-layout-fix.css'; import './final-release-polish.css'; import './owner-job-card-mobile-alignment.css'; import './job-guidance-editorial.css'; import './page-top-control-consistency.css'; import './native-app-topbar-final.css'; import './boxed-content-spacing-final.css'; import './ask-everitt-overlay-fix.css'; import './linkedin-mobile-refresh.css'; import './desktop-auth-contrast.css';
import './release-polish.css';
import './unified-record-cards.css';
import './final-record-card-consistency.css';
import './hero-background-visibility.css';
import './post-login-visual-unification.css';
import './post-login-surface-consistency.css';
import './final-cross-role-header-controls.css';
import './native-app-readability-2026.css';
import './contractor-field-mode.css';
import './quote-workspace.css';
import './role-home-structure.css';
import './signed-in-canvas.css';
import './hero-last.css';
import './jobs-filter-mobile-alignment.css';
import './footer-contrast-final.css';
import './footer-bottom-nav-clearance.css';
import './unified-spacing-final.css';
import './jobs-mobile-editorial-final.css';

const manrope = Manrope({ subsets: ['latin', 'vietnamese'], weight: ['400', '500', '600', '700', '800'], variable: '--font-manrope', display: 'swap' });
export const viewport: Viewport = { width: 'device-width', initialScale: 1, viewportFit: 'cover', themeColor: '#243F53' };
export const metadata: Metadata = { title: 'EverittOS | Run Your Service Business', description: 'Manage requests, customers, jobs, schedules, photos, and payments in one simple workspace.', manifest: '/manifest.webmanifest', appleWebApp: { capable: true, title: 'EverittOS', statusBarStyle: 'default' }, other: { 'mobile-web-app-capable': 'yes' }, icons: { icon: [{ url: '/favicon.ico', sizes: 'any' }, { url: '/icon.png', type: 'image/png', sizes: '512x512' }], apple: [{ url: '/apple-icon.png', type: 'image/png', sizes: '180x180' }], shortcut: '/favicon.ico' } };

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const deployment = vercelDeploymentEnv();
  const cookieStore = await cookies();
  const initialLocale = normalizeLocale(cookieStore.get(LOCALE_COOKIE_NAME)?.value);
  return <html lang={initialLocale} data-locale={initialLocale} data-deployment={deployment} className={manrope.variable}><body className={manrope.className} data-locale={initialLocale}><SupabaseRuntimeConfig /><PwaRegistration /><MobileDocumentFlags /><NativeAppProvider /><NativePinLock /><AppConnectivityBanner /><NetworkStatusBanner /><PwaUpdatePrompt /><SuppressVercelToolbar /><LocaleProvider initialLocale={initialLocale}><JobFinanceWordingAndCustomerRate /><CreateFormCancelControls /><ContractorJobPayVisibility /><ExpensesListEnhancer /><AskEverittQuickClear /><ToastProvider><LocaleSync /><SessionGuard><ActivityHeartbeat /><WorkspacePlanProvider><WorkspaceBootstrap /><SkipToMain /><SiteChrome /><ContractorStaticSections />{children}<MobileBottomNav /><AnalyticsGate /><CookieConsentBanner /></WorkspacePlanProvider></SessionGuard></ToastProvider></LocaleProvider></body></html>;
}
