'use client';

import { useEffect, useId, useRef, useState } from 'react';
import { downloadExportFromApi } from '@/lib/exports/client-download';
import { getExportCopy } from '@/lib/i18n/export-copy';
import type { Locale } from '@/lib/i18n/config';
import { requireNativeStepUp } from '@/lib/native-step-up';

export type ExportMenuProps = { endpoint:string; query?:string|URLSearchParams|Record<string,string|null|undefined>; locale?:Locale; disabled?:boolean; className?:string; labels?:{export?:string;csv?:string;pdf?:string}; onError?:(message:string)=>void; onSuccess?:(format:'csv'|'pdf'|'share')=>void };
type MenuPosition={left:number;top:number;width:number};
const menuButtonStyle={appearance:'none' as const,WebkitAppearance:'none' as const,display:'flex',alignItems:'center',justifyContent:'flex-start',width:'100%',minWidth:0,maxWidth:'100%',margin:0,padding:'12px 14px',border:0,borderRadius:8,background:'transparent',boxSizing:'border-box' as const,color:'var(--text, #142635)',font:'inherit',fontWeight:600,lineHeight:1.2,textAlign:'left' as const,textIndent:0,whiteSpace:'normal' as const,overflow:'visible',transform:'none',cursor:'pointer'};
function queryRecord(query:ExportMenuProps['query']):Record<string,string>{const params=new URLSearchParams();if(query instanceof URLSearchParams)query.forEach((v,k)=>{if(v)params.set(k,v)});else if(typeof query==='string'&&query.trim())new URLSearchParams(query.startsWith('?')?query.slice(1):query).forEach((v,k)=>{if(v)params.set(k,v)});else if(query&&typeof query==='object')for(const[k,v]of Object.entries(query))if(v!=null&&v!=='')params.set(k,String(v));const out:Record<string,string>={};params.forEach((v,k)=>out[k]=v);return out}
function buildUrl(endpoint:string,query:ExportMenuProps['query'],format:'csv'|'pdf',locale?:Locale){const params=new URLSearchParams(queryRecord(query));params.set('format',format);if(locale)params.set('locale',locale);const qs=params.toString();return qs?`${endpoint}?${qs}`:`${endpoint}?format=${format}`}
export function ExportMenu({endpoint,query,locale='en',disabled=false,className,labels,onError,onSuccess}:ExportMenuProps){const copy=getExportCopy(locale);const[open,setOpen]=useState(false);const[shareOpen,setShareOpen]=useState(false);const[email,setEmail]=useState('');const[shareMessage,setShareMessage]=useState('');const[busy,setBusy]=useState<'csv'|'pdf'|'share-csv'|'share-pdf'|null>(null);const[menuPosition,setMenuPosition]=useState<MenuPosition|null>(null);const rootRef=useRef<HTMLDivElement|null>(null);const menuId=useId();
useEffect(()=>{if(!open)return;function down(e:MouseEvent){if(!rootRef.current?.contains(e.target as Node)){setOpen(false);setShareOpen(false);setShareMessage('')}}function key(e:KeyboardEvent){if(e.key==='Escape'){setOpen(false);setShareOpen(false);setShareMessage('')}}document.addEventListener('mousedown',down);document.addEventListener('keydown',key);return()=>{document.removeEventListener('mousedown',down);document.removeEventListener('keydown',key)}},[open]);
useEffect(()=>{if(!open){setMenuPosition(null);return}function update(){const root=rootRef.current;if(!root)return;const rect=root.getBoundingClientRect(),pad=12,desired=shareOpen?260:190,available=Math.max(0,window.innerWidth-pad*2),width=Math.min(desired,available),maxLeft=Math.max(pad,window.innerWidth-width-pad);setMenuPosition({left:Math.min(Math.max(pad,rect.left),maxLeft),top:rect.bottom+4,width})}update();window.addEventListener('resize',update);window.addEventListener('scroll',update,true);return()=>{window.removeEventListener('resize',update);window.removeEventListener('scroll',update,true)}},[open,shareOpen]);
async function runExport(format:'csv'|'pdf'){if(disabled||busy)return;if(!(await requireNativeStepUp('Confirm to export EverittOS data')))return;setBusy(format);setOpen(false);setShareOpen(false);const result=await downloadExportFromApi(buildUrl(endpoint,query,format,locale),{fallbackFilename:`everittos-export.${format==='pdf'?'html':'csv'}`});setBusy(null);if(!result.ok){onError?.(result.error||copy.exportFailed);return}onSuccess?.(format)}
async function runShare(format:'csv'|'pdf'){if(disabled||busy)return;if(!(await requireNativeStepUp('Confirm to share EverittOS data')))return;setShareMessage('');setBusy(format==='csv'?'share-csv':'share-pdf');let response:Response;try{response=await fetch('/api/exports/share',{method:'POST',cache:'no-store',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({endpoint,format,to:email,query:queryRecord(query),locale})})}catch{setBusy(null);setShareMessage(copy.shareFailed);onError?.(copy.shareFailed);return}const json=(await response.json().catch(()=>({})))as{error?:string;code?:string};setBusy(null);if(!response.ok){const message=json.error||copy.shareFailed;setShareMessage(message);onError?.(message);return}setShareMessage(copy.shareSent);setOpen(false);setShareOpen(false);onSuccess?.('share')}
const isDisabled=disabled||Boolean(busy);const triggerLabel=busy?(String(busy).startsWith('share')?copy.sending:copy.preparingExport):labels?.export||copy.export;
return <div ref={rootRef} className={className} style={{position:'relative',display:'inline-block'}}><button type="button" className="btn" disabled={isDisabled} aria-haspopup="menu" aria-expanded={open} aria-controls={menuId} onClick={()=>{setOpen(v=>!v);setShareOpen(false);setShareMessage('')}}>{triggerLabel}</button>{open?<div id={menuId} role="menu" style={{position:'fixed',left:menuPosition?.left??12,top:menuPosition?.top??0,width:menuPosition?.width??190,maxWidth:'calc(100vw - 24px)',boxSizing:'border-box',zIndex:1000,background:'var(--surface, #fff)',border:'1px solid var(--border, #e4e1d8)',borderRadius:10,boxShadow:'0 8px 24px rgba(36, 37, 34, 0.12)',padding:6,overflow:'hidden'}}><button type="button" role="menuitem" style={menuButtonStyle} disabled={isDisabled} onClick={()=>void runExport('csv')}>{labels?.csv||copy.exportCsv}</button><button type="button" role="menuitem" style={menuButtonStyle} disabled={isDisabled} onClick={()=>void runExport('pdf')}>{labels?.pdf||copy.exportPdf}</button><button type="button" role="menuitem" style={menuButtonStyle} disabled={isDisabled} onClick={()=>{setShareOpen(true);setShareMessage('')}}>{copy.shareByEmail}</button>{shareOpen?<form style={{display:'grid',gap:6,padding:6,width:'100%',maxWidth:'100%',boxSizing:'border-box'}} onSubmit={e=>{e.preventDefault();void runShare('pdf')}}><label className="muted" htmlFor={`${menuId}-email`} style={{fontSize:12}}>{copy.emailAddress}</label><input id={`${menuId}-email`} className="input" type="email" autoComplete="email" value={email} aria-label={copy.emailAddress} onChange={e=>setEmail(e.target.value)} disabled={isDisabled} style={{width:'100%',maxWidth:'100%',minWidth:0,boxSizing:'border-box'}}/><div style={{display:'flex',gap:6,flexWrap:'wrap'}}><button type="button" className="btn" disabled={isDisabled} onClick={()=>void runShare('csv')}>{busy==='share-csv'?copy.sending:copy.sendCsv}</button><button type="submit" className="btn" disabled={isDisabled}>{busy==='share-pdf'?copy.sending:copy.sendPdf}</button></div>{shareMessage?<p className="muted" style={{margin:0,fontSize:12}}>{shareMessage}</p>:null}</form>:null}</div>:null}</div>}
