'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAppFeedback } from '@/components/feedback/use-app-feedback';
import { useLocale } from '@/components/locale-provider';
import { LEAD_SOURCE_OPTIONS } from '@/lib/lead-sources';
import { getLeadFormCopy,leadSourceLabelForLocale } from '@/lib/i18n/team-lead-copy';
import { useTeamOptions } from '@/lib/team-options-client';
import { ensureWorkspaceForSave } from '@/lib/workspace-client';
import { supabase } from '@/lib/supabase';
type RequestCreateFormProps={onCreated?:(requestId:string)=>void;redirectTo?:string};
export function RequestCreateForm({onCreated,redirectTo='/leads'}:RequestCreateFormProps){const router=useRouter();const appFeedback=useAppFeedback();const {locale}=useLocale();const c=getLeadFormCopy(locale);const {teamOptions,teamOptionsLoading}=useTeamOptions();const [displayName,setDisplayName]=useState('');const [email,setEmail]=useState('');const [phone,setPhone]=useState('');const [address,setAddress]=useState('');const [notes,setNotes]=useState('');const [assignedTo,setAssignedTo]=useState('');const [requestSource,setRequestSource]=useState('website');const [saving,setSaving]=useState(false);
async function saveRequest(){if(saving)return;if(!displayName.trim()){appFeedback.error(c.nameRequired);return;}setSaving(true);const {data:auth}=await supabase.auth.getUser();const user=auth.user;if(!user){setSaving(false);router.push('/login?next=/leads/new');return;}const workspace=await ensureWorkspaceForSave(user.id);if(!workspace.ok){setSaving(false);appFeedback.error(workspace.error);return;}const res=await fetch('/api/customers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({displayName,email,phone,address,notes,assigned_to:assignedTo||null,pipeline_stage:'open',lead_source:requestSource,record_type:'lead'})});const json=(await res.json()) as {customer?:{id:string};error?:string;message?:string};setSaving(false);if(!res.ok){appFeedback.error(json.error||c.saveError);return;}appFeedback.created();setDisplayName('');setEmail('');setPhone('');setAddress('');setNotes('');setAssignedTo('');setRequestSource('website');if(json.customer?.id){onCreated?.(json.customer.id);const nextPath=redirectTo==='/leads'?`/leads/${json.customer.id}`:redirectTo;setTimeout(()=>router.push(nextPath),600);}else appFeedback.error(c.savedOpenError);}
return <div className="card form request-create-form" style={{gap:'18px'}}><h3 className="card-title-sm" style={{margin:'0 0 4px'}}>{c.details}</h3><input className="input" placeholder={c.name} value={displayName} onChange={e=>setDisplayName(e.target.value)}/><input className="input" placeholder={c.email} type="email" value={email} onChange={e=>setEmail(e.target.value)}/><input className="input" placeholder={c.phone} value={phone} onChange={e=>setPhone(e.target.value)}/><input className="input" placeholder={c.address} value={address} onChange={e=>setAddress(e.target.value)}/><div className="form-group" style={{gap:'8px'}}><label htmlFor="request-assigned-to">{c.assignTo}</label><select id="request-assigned-to" className="input" value={assignedTo} disabled={teamOptionsLoading} onChange={e=>setAssignedTo(e.target.value)}><option value="">{c.unassigned}</option>{teamOptions.map(member=><option key={member.userId} value={member.userId}>{member.label} - {member.role}</option>)}</select></div><div className="form-group" style={{gap:'8px'}}><label htmlFor="request-source">{c.source}</label><select id="request-source" className="input" value={requestSource} onChange={e=>setRequestSource(e.target.value)}>{LEAD_SOURCE_OPTIONS.map(opt=><option key={opt.value} value={opt.value}>{leadSourceLabelForLocale(opt.value,locale)}</option>)}</select></div><textarea className="input" rows={4} placeholder={c.notes} value={notes} onChange={e=>setNotes(e.target.value)}/><button type="button" className="btn btn-primary" style={{marginTop:'4px'}} disabled={saving} onClick={()=>void saveRequest()}>{saving?c.saving:c.save}</button></div>;
}
export const LeadCreateForm=RequestCreateForm;
