'use client';

import { PhotoComparisonSection } from '@/components/before-after-comparison';
import { EmptyState } from '@/components/empty-state';
import { useTranslation } from '@/components/locale-provider';
import { getCommonUiCopy } from '@/lib/i18n/common-ui-copy';
import type { Locale } from '@/lib/i18n/config';
import type { JobPhotoView } from '@/lib/job-photos-types';
import { fetchJobPhotosWithUrls, resolvePhotoType } from '@/lib/job-photos-client';
import { JOB_PHOTO_TAGS, photoTagLabel } from '@/lib/job-photo-tags';
import { friendlyErrorMessage } from '@/lib/user-errors';
import { supabase } from '@/lib/supabase';
import { useEffect, useMemo, useRef, useState } from 'react';

type PhotoGalleryProps={jobId:string;refreshKey?:number;showComparison?:boolean;showMetadata?:boolean;canView?:boolean;customerOnly?:boolean};
type PhotoGalleryCopy={notShared:string;loading:string;emptyTitle:string;emptyDescription:string;photoAlt:string;by:string;close:string;previous:string;next:string};
const PHOTO_GALLERY_COPY:Record<Locale,PhotoGalleryCopy>={en:{notShared:'Photos are not shared for this job.',loading:'Loading photos…',emptyTitle:'No photos yet',emptyDescription:'Before and after photos will appear here when they are shared.',photoAlt:'photo',by:'By',close:'Close',previous:'Previous',next:'Next'},es:{notShared:'No se compartieron fotos para este trabajo.',loading:'Cargando fotos…',emptyTitle:'Aún no hay fotos',emptyDescription:'Las fotos del antes y después aparecerán aquí cuando se compartan.',photoAlt:'foto',by:'Por',close:'Cerrar',previous:'Anterior',next:'Siguiente'},vi:{notShared:'Hình ảnh chưa được chia sẻ cho công việc này.',loading:'Đang tải hình ảnh…',emptyTitle:'Chưa có hình ảnh',emptyDescription:'Hình ảnh trước và sau khi hoàn thành sẽ xuất hiện tại đây khi được chia sẻ.',photoAlt:'hình ảnh',by:'Bởi',close:'Đóng',previous:'Trước',next:'Sau'}};
const SWIPE_THRESHOLD_PX=48;
function formatPhotoWhen(value:string|null,locale:Locale){return value?new Date(value).toLocaleString(locale):'';}
function formatFileSize(bytes:number|null|undefined){if(!bytes||bytes<=0)return '';if(bytes<1024)return `${bytes} B`;if(bytes<1024*1024)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/(1024*1024)).toFixed(1)} MB`;}
export function PhotoGallery({jobId,refreshKey=0,showComparison=true,showMetadata=true,canView=true,customerOnly=false}:PhotoGalleryProps){const {locale}=useTranslation();const copy=PHOTO_GALLERY_COPY[locale];const common=getCommonUiCopy(locale);const [photos,setPhotos]=useState<JobPhotoView[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [previewIndex,setPreviewIndex]=useState<number|null>(null);const touchStartX=useRef<number|null>(null);
useEffect(()=>{if(!canView){setPhotos([]);setLoading(false);return;}async function load(){setLoading(true);setError('');const {photos:loaded,error:fetchError}=await fetchJobPhotosWithUrls(supabase,jobId,{customerOnly});if(fetchError){setError(fetchError);setLoading(false);return;}setPhotos(loaded.filter(p=>p.url));setLoading(false);}void load();},[jobId,refreshKey,canView,customerOnly]);
const orderedPhotos=useMemo(()=>JOB_PHOTO_TAGS.flatMap(tag=>photos.filter(photo=>resolvePhotoType(photo)===tag).sort((a,b)=>String(b.created_at||'').localeCompare(String(a.created_at||'')))),[photos]);const previewPhoto=previewIndex!==null?orderedPhotos[previewIndex]:null;
useEffect(()=>{if(previewIndex===null)return;const previousOverflow=document.body.style.overflow;document.body.style.overflow='hidden';function handleKeyDown(event:KeyboardEvent){if(event.key==='Escape'){setPreviewIndex(null);return;}if(event.key==='ArrowLeft'){setPreviewIndex(current=>current===null?current:Math.max(0,current-1));return;}if(event.key==='ArrowRight')setPreviewIndex(current=>current===null?current:Math.min(orderedPhotos.length-1,current+1));}window.addEventListener('keydown',handleKeyDown);return()=>{window.removeEventListener('keydown',handleKeyDown);document.body.style.overflow=previousOverflow;};},[previewIndex,orderedPhotos.length]);
function handleTouchStart(e:React.TouchEvent<HTMLDivElement>){touchStartX.current=e.changedTouches[0]?.clientX??null;}function handleTouchEnd(e:React.TouchEvent<HTMLDivElement>){if(touchStartX.current===null)return;const endX=e.changedTouches[0]?.clientX;if(endX===undefined){touchStartX.current=null;return;}const distance=endX-touchStartX.current;touchStartX.current=null;if(Math.abs(distance)<SWIPE_THRESHOLD_PX)return;if(distance>0){setPreviewIndex(current=>current===null?current:Math.max(0,current-1));return;}setPreviewIndex(current=>current===null?current:Math.min(orderedPhotos.length-1,current+1));}
if(!canView)return <p className="muted">{copy.notShared}</p>;if(loading)return <p className="loading-state" role="status">{copy.loading}</p>;if(error)return <p className="auth-message auth-message-error" role="alert">{friendlyErrorMessage(error)}</p>;if(!photos.length)return <EmptyState title={copy.emptyTitle} description={copy.emptyDescription}/>;
return <div className="photo-gallery-readonly">{showComparison?<PhotoComparisonSection photos={photos}/>:null}{JOB_PHOTO_TAGS.map(tag=>{const items=orderedPhotos.filter(photo=>resolvePhotoType(photo)===tag);if(!items.length)return null;return <div key={tag} className="photo-tag-group"><h4>{photoTagLabel(tag)} ({items.length})</h4><div className="photo-grid photo-grid-large">{items.map(photo=>{const photoType=resolvePhotoType(photo);const absoluteIndex=orderedPhotos.findIndex(row=>row.id===photo.id);return <figure key={photo.id} className="photo-thumb"><button type="button" className="photo-thumb-open" onClick={()=>setPreviewIndex(absoluteIndex)} aria-label={`${photoTagLabel(photoType)} ${copy.photoAlt}`}><img src={photo.url} alt={`${photoTagLabel(photoType)} ${copy.photoAlt}`} loading="lazy"/></button><figcaption><span className="photo-tag-pill">{photoTagLabel(photoType)}</span>{showMetadata?<><span className="photo-meta-line">{formatPhotoWhen(photo.created_at,locale)}</span>{photo.uploader_display_name?<span className="photo-meta-line">{copy.by} {photo.uploader_display_name}</span>:null}{photo.file_size_bytes?<span className="photo-meta-line">{formatFileSize(photo.file_size_bytes)}</span>:null}</>:null}</figcaption></figure>})}</div></div>})}{previewPhoto?.url?<div className="photo-lightbox" role="dialog" aria-modal="true" aria-label={common.photoPreview} onClick={()=>setPreviewIndex(null)}><div className="photo-lightbox-panel" onClick={e=>e.stopPropagation()} onTouchStart={handleTouchStart} onTouchEnd={handleTouchEnd}><div className="photo-lightbox-toolbar"><span>{photoTagLabel(resolvePhotoType(previewPhoto))}{previewPhoto.uploader_display_name?` · ${copy.by} ${previewPhoto.uploader_display_name}`:''}</span><button type="button" className="btn" onClick={()=>setPreviewIndex(null)} autoFocus>{copy.close}</button></div><img src={previewPhoto.url} alt={`${photoTagLabel(resolvePhotoType(previewPhoto))} ${copy.photoAlt}`}/><div className="photo-lightbox-nav"><button type="button" className="btn" disabled={previewIndex===null||previewIndex<=0} onClick={()=>setPreviewIndex(current=>current===null?current:Math.max(0,current-1))}>{copy.previous}</button><span className="muted">{(previewIndex??0)+1} / {orderedPhotos.length}</span><button type="button" className="btn" disabled={previewIndex===null||previewIndex>=orderedPhotos.length-1} onClick={()=>setPreviewIndex(current=>current===null?current:Math.min(orderedPhotos.length-1,current+1))}>{copy.next}</button></div><p className="muted">{[formatPhotoWhen(previewPhoto.created_at,locale),formatFileSize(previewPhoto.file_size_bytes)].filter(Boolean).join(' · ')}</p></div></div>:null}</div>;
}
