/** Structured activation logs for Vercel function output (grep-friendly). */
export function logBillingActivation(
  tag:
    | 'WEBHOOK_RECEIVED'
    | 'WEBHOOK_SYNC_SUCCESS'
    | 'WEBHOOK_SYNC_FAILED'
    | 'CHECKOUT_RETURN_SYNC'
    | 'CHECKOUT_RETURN_SYNC_FAILED'
    | 'CHECKOUT_RETURN_SYNC_DIRECT_RECOVERY_STARTED'
    | 'CHECKOUT_DIRECT_RECOVERY_SESSION_READ'
    | 'CHECKOUT_DIRECT_RECOVERY_PLAN_MISSING'
    | 'CHECKOUT_DIRECT_RECOVERY_PROFILE_FAILED'
    | 'CHECKOUT_DIRECT_RECOVERY_ORG_FAILED'
    | 'CHECKOUT_DIRECT_RECOVERY_SUBSCRIPTION_ROW_FAILED'
    | 'CHECKOUT_DIRECT_RECOVERY_SUCCESS'
    | 'CHECKOUT_DIRECT_RECOVERY_CRASHED',
  data: Record<string, unknown> = {}
) {
  console.log(tag, data);
}
