export const CATCH_FEATURE = 'catchGrowth' as const;
export const CATCH_REQUIRED_PLAN = 'enterprise' as const;
export const CATCH_PRODUCT_NAME = 'Scout';
export const CATCH_PRODUCT_LINE = 'Scout watches your EverittOS work and shows you who needs attention next.';
export const CATCH_STAGES=[{id:'inquiry',label:'Inquiry',href:'/leads',hint:'New requests waiting for a reply.'},{id:'booking',label:'Booking',href:'/bookings',hint:'Customers waiting for a date or confirmation.'},{id:'customer',label:'Customer',href:'/customers',hint:'People ready for current or repeat work.'},{id:'job',label:'Job',href:'/jobs',hint:'Work that needs to be scheduled, started, or finished.'},{id:'followup',label:'Follow-up',href:'/catch',hint:'Completed work or quiet customers who need a follow-up.'}] as const;
export type CatchStageId=(typeof CATCH_STAGES)[number]['id'];export type CatchRecordKind='lead'|'booking'|'customer'|'job';
export type CatchRecord={id:string;kind:CatchRecordKind;name:string;stage:CatchStageId;status?:string|null;email?:string|null;phone?:string|null;updatedAt?:string|null;createdAt?:string|null;href:string};
export type CatchAction={id:string;title:string;reason:string;stage:CatchStageId;href:string;message:string;priority:number};
export type CatchSnapshot={counts:Record<CatchStageId,number>;conversionRate:number;agingInquiries:number;followUpsDue:number;actions:CatchAction[]};
const STALE_INQUIRY_HOURS=24,STALE_FOLLOWUP_HOURS=72;
export function hoursSince(iso?:string|null,now=Date.now()):number{if(!iso)return Number.POSITIVE_INFINITY;const parsed=new Date(iso).getTime();if(Number.isNaN(parsed))return Number.POSITIVE_INFINITY;return Math.max(0,(now-parsed)/36e5);}
export function isOpenLeadStatus(status?:string|null):boolean{return['open','contacted','qualified','proposal_sent','negotiation','reopened','lead'].includes((status||'open').toLowerCase());}
export function outreachDraft(name:string,stage:CatchStageId):string{const first=name.split(/\s+/)[0]||'there';if(stage==='inquiry')return`Hi ${first}, thanks for reaching out. I can hold a visit this week if you share the address and what you need done.`;if(stage==='booking')return`Hi ${first}, confirming your booking. Reply YES to lock the window, or tell me a better time.`;if(stage==='job')return`Hi ${first}, the crew is lined up. I will send a photo update when the visit starts.`;return`Hi ${first}, thank you for the work. If the visit looks right, a short review helps the next customer choose us.`;}
export function buildCatchSnapshot(records:CatchRecord[],now=Date.now()):CatchSnapshot{const counts:Record<CatchStageId,number>={inquiry:0,booking:0,customer:0,job:0,followup:0};const actions:CatchAction[]=[];for(const record of records){counts[record.stage]+=1;const age=hoursSince(record.updatedAt||record.createdAt,now);if(record.kind==='lead'&&isOpenLeadStatus(record.status)&&age>=STALE_INQUIRY_HOURS)actions.push({id:`reply-${record.id}`,title:`Reply to ${record.name}`,reason:age>=72?'Quiet for 3+ days':'No first reply in 24 hours',stage:'inquiry',href:record.href,message:outreachDraft(record.name,'inquiry'),priority:age>=72?1:2});if(record.kind==='booking'&&/pending|requested|new/i.test(record.status||'pending'))actions.push({id:`confirm-${record.id}`,title:`Confirm booking for ${record.name}`,reason:'Booking is waiting on a confirmation',stage:'booking',href:record.href,message:outreachDraft(record.name,'booking'),priority:2});if(record.kind==='job'&&/scheduled|assigned|in_progress|in-progress/i.test(record.status||''))actions.push({id:`advance-${record.id}`,title:`Move ${record.name} forward`,reason:'Job is open and needs a next field action',stage:'job',href:record.href,message:outreachDraft(record.name,'job'),priority:3});if(record.kind==='job'&&/complete|done|finished/i.test(record.status||'')&&age>=STALE_FOLLOWUP_HOURS){actions.push({id:`review-${record.id}`,title:`Ask ${record.name} for a review`,reason:'Completed work with no follow-up yet',stage:'followup',href:record.href,message:outreachDraft(record.name,'followup'),priority:2});counts.followup+=1;}}const converted=counts.customer+counts.job,topOfFunnel=counts.inquiry+converted,conversionRate=topOfFunnel===0?0:Math.round(converted/topOfFunnel*100);actions.sort((a,b)=>a.priority-b.priority||a.title.localeCompare(b.title));return{counts,conversionRate,agingInquiries:actions.filter(a=>a.stage==='inquiry').length,followUpsDue:actions.filter(a=>a.stage==='followup'||a.stage==='booking').length,actions:actions.slice(0,12)};}
