import type { CatchActionCopy } from '@/lib/i18n/catch-copy';

export const CATCH_FEATURE = 'catchGrowth' as const;
export const CATCH_REQUIRED_PLAN = 'enterprise' as const;
export type CatchStageId = 'inquiry' | 'booking' | 'customer' | 'job' | 'followup';
export type CatchRecordKind = 'lead' | 'booking' | 'customer' | 'job';
export type CatchRecord = { id:string; kind:CatchRecordKind; name:string; stage:CatchStageId; status?:string|null; email?:string|null; phone?:string|null; updatedAt?:string|null; createdAt?:string|null; href:string; contactName?:string|null; jobTitle?:string|null; customerId?:string|null };
export type CatchAction = { id:string; title:string; reason:string; stage:CatchStageId; href:string; message:string; priority:number; email?:string|null; customerId?:string|null; jobId?:string|null };
export type CatchSnapshot = { actions:CatchAction[] };
const STALE_INQUIRY_HOURS=24, STALE_FOLLOWUP_HOURS=72, STALE_CUSTOMER_HOURS=24*60;
export function hoursSince(iso?:string|null,now=Date.now()):number{if(!iso)return Number.POSITIVE_INFINITY;const parsed=new Date(iso).getTime();if(Number.isNaN(parsed))return Number.POSITIVE_INFINITY;return Math.max(0,(now-parsed)/36e5);}
export function isOpenLeadStatus(status?:string|null):boolean{return['open','contacted','qualified','proposal_sent','negotiation','reopened','lead'].includes((status||'open').toLowerCase());}
export function buildCatchSnapshot(records:CatchRecord[],copy:CatchActionCopy,now=Date.now()):CatchSnapshot{const actions:CatchAction[]=[];for(const record of records){const age=hoursSince(record.updatedAt||record.createdAt,now);const base={email:record.email,customerId:record.customerId||((record.kind==='lead'||record.kind==='customer')?record.id:null)};if(record.kind==='lead'&&isOpenLeadStatus(record.status)&&age>=STALE_INQUIRY_HOURS)actions.push({...base,id:`reply-${record.id}`,title:copy.leadTitle(record.name),reason:age>=72?copy.leadOldReason:copy.leadNewReason,stage:'inquiry',href:record.href,message:copy.inquiryDraft(record.name),priority:age>=72?1:2});if(record.kind==='booking'&&/pending|requested|new/i.test(record.status||'pending'))actions.push({...base,id:`confirm-${record.id}`,title:copy.bookingTitle(record.name),reason:copy.bookingReason,stage:'booking',href:record.href,message:copy.bookingDraft(record.name),priority:2});if(record.kind==='job'&&/scheduled|assigned|in_progress|in-progress/i.test(record.status||''))actions.push({...base,jobId:record.id,id:`advance-${record.id}`,title:copy.jobTitle(record.name),reason:copy.jobReason,stage:'job',href:record.href,message:copy.jobDraft(record.contactName||record.name),priority:3});if(record.kind==='job'&&record.contactName&&/complete|done|finished/i.test(record.status||'')&&age>=STALE_FOLLOWUP_HOURS){const jobLabel=record.jobTitle||record.name;actions.push({...base,jobId:record.id,id:`review-${record.id}`,title:copy.followUpTitle(jobLabel,record.contactName),reason:copy.followUpReason,stage:'followup',href:record.href,message:copy.followUpDraft(record.contactName),priority:2});}if(record.kind==='customer'&&age>=STALE_CUSTOMER_HOURS)actions.push({...base,id:`return-${record.id}`,title:copy.returnTitle(record.name),reason:copy.returnReason,stage:'customer',href:record.href,message:copy.returnDraft(record.name),priority:4});}actions.sort((a,b)=>a.priority-b.priority||a.title.localeCompare(b.title));return{actions:actions.slice(0,24)};}
