/** Deep links from dashboard KPI cards to their supporting records. */
export const DASHBOARD_LINKS = {
  completedWeek: '/jobs?status=completed&period=week',
  completedJobs: '/jobs?status=completed',
  revenueMonth: '/dashboard/details?metric=collected',
  paidToYou: '/dashboard/details?metric=collected',
  customerInvoices: '/dashboard/details?metric=invoiced',
  stillOwed: '/dashboard/details?metric=outstanding',
  latePayments: '/dashboard/details?metric=late',
  unpaidInvoices: '/dashboard/details?metric=unpaid-invoices',
  cashAfterExpenses: '/dashboard/details?metric=net-cash',
  estimatedProfit: '/dashboard/details?metric=estimated-profit',
  contractorPay: '/dashboard/details?metric=contractor-pay',
  contractorPayOwed: '/dashboard/details?metric=contractor-pay-owed',
  contractorPayPending: '/dashboard/details?metric=contractor-pay-pending',
  otherExpenses: '/dashboard/details?metric=expenses',
  newCustomersMonth: '/customers?period=month',
  openInvoices: '/dashboard/details?metric=unpaid-invoices',
  scheduledUpcoming: '/schedule?range=upcoming',
  upcomingJobs: '/schedule?range=upcoming',
  todayTasks: '/projects',
  notifications: '/notifications',
  customers: '/customers',
  activeCustomers: '/dashboard/details?metric=active-customers',
  customersLeads: '/customers?stage=lead',
  people: '/people',
  workers: '/people',
  proposals: '/proposals',
  bookings: '/bookings',
  messages: '/messages',
  jobs: '/jobs',
  reports: '/jobs'
} as const;
