/** Deep links from dashboard KPI cards to filtered list views. */
export const DASHBOARD_LINKS = {
  completedWeek: '/jobs?status=completed&period=week',
  completedJobs: '/jobs?status=completed',
  revenueMonth: '/invoices?payment=history',
  paidToYou: '/invoices?payment=history',
  customerInvoices: '/invoices',
  stillOwed: '/invoices?payment=unpaid&focus=outstanding',
  latePayments: '/invoices?payment=overdue&focus=outstanding',
  unpaidInvoices: '/invoices?payment=unpaid&focus=outstanding',
  cashAfterExpenses: '/analytics',
  estimatedProfit: '/analytics',
  contractorPay: '/contractor-pay?status=all',
  contractorPayOwed: '/contractor-pay?status=unpaid',
  contractorPayPending: '/contractor-pay?status=pending',
  otherExpenses: '/expenses',
  newCustomersMonth: '/customers?period=month',
  openInvoices: '/invoices?payment=unpaid&focus=outstanding',
  scheduledUpcoming: '/schedule?range=upcoming',
  upcomingJobs: '/schedule?range=upcoming',
  todayTasks: '/projects',
  notifications: '/notifications',
  customers: '/customers',
  activeCustomers: '/customers',
  customersLeads: '/customers?stage=lead',
  people: '/people',
  workers: '/people',
  proposals: '/proposals',
  bookings: '/bookings',
  messages: '/messages',
  jobs: '/jobs',
  reports: '/jobs'
} as const;
