import type { Locale } from '@/lib/i18n/config';

export const quoteFieldCopy = {
  en: {
    pricingInputs: 'Pricing inputs',
    unitSqft: 'sq ft',
    unitHours: 'hours',
    unitRooms: 'rooms',
    unitItems: 'items',
    unitLoads: 'loads',
    unitLinear: 'linear ft',
    unitAcres: 'acres',
    unitProperties: 'properties',
    unitVehicles: 'vehicles',
    unitUnits: 'units',
    light: 'Light',
    average: 'Average',
    heavy: 'Heavy',
    postConstruction: 'Post-construction',
    oneTime: 'One-time',
    weekly: 'Weekly',
    biWeekly: 'Every 2 weeks',
    monthly: 'Monthly',
    countryTitle: 'Country, region, and profession',
    profession: 'Profession / service',
    customProfession: 'Custom profession',
    customPlaceholder: 'Type your profession or service',
    selectProfession: 'Select profession',
    other: 'Other',
    country: 'Country',
    region: 'Region',
    city: 'City',
    paidHelp: 'Public wage and price sources follow the country you set. Profession shapes the quote helper.',
    freeHelp: 'Basic quote help is available on this plan. Pro unlocks country sources, region, and similar-job history.',
    publicSources: 'Public sources for this country'
  },
  es: {
    pricingInputs: 'Datos de precio',
    unitSqft: 'pies²',
    unitHours: 'horas',
    unitRooms: 'habitaciones',
    unitItems: 'artículos',
    unitLoads: 'cargas',
    unitLinear: 'pies lineales',
    unitAcres: 'acres',
    unitProperties: 'propiedades',
    unitVehicles: 'vehículos',
    unitUnits: 'unidades',
    light: 'Ligero',
    average: 'Promedio',
    heavy: 'Pesado',
    postConstruction: 'Postconstrucción',
    oneTime: 'Una vez',
    weekly: 'Semanal',
    biWeekly: 'Cada 2 semanas',
    monthly: 'Mensual',
    countryTitle: 'País, región y profesión',
    profession: 'Profesión / servicio',
    customProfession: 'Profesión personalizada',
    customPlaceholder: 'Escribe tu profesión o servicio',
    selectProfession: 'Seleccionar profesión',
    other: 'Otro',
    country: 'País',
    region: 'Región',
    city: 'Ciudad',
    paidHelp: 'Las fuentes públicas de salarios y precios siguen el país que elijas. La profesión orienta la cotización.',
    freeHelp: 'Esta plan incluye ayuda básica. Pro desbloquea fuentes por país, región e historial de trabajos similares.',
    publicSources: 'Fuentes públicas para este país'
  },
  vi: {
    pricingInputs: 'Thông số giá',
    unitSqft: 'ft²',
    unitHours: 'giờ',
    unitRooms: 'phòng',
    unitItems: 'món',
    unitLoads: 'mẻ',
    unitLinear: 'ft dài',
    unitAcres: 'mẫu',
    unitProperties: 'bất động sản',
    unitVehicles: 'xe',
    unitUnits: 'đơn vị',
    light: 'Nhẹ',
    average: 'Trung bình',
    heavy: 'Nặng',
    postConstruction: 'Sau xây dựng',
    oneTime: 'Một lần',
    weekly: 'Hàng tuần',
    biWeekly: 'Mỗi 2 tuần',
    monthly: 'Hàng tháng',
    countryTitle: 'Quốc gia, khu vực và nghề',
    profession: 'Nghề / dịch vụ',
    customProfession: 'Nghề tùy chỉnh',
    customPlaceholder: 'Nhập nghề hoặc dịch vụ',
    selectProfession: 'Chọn nghề',
    other: 'Khác',
    country: 'Quốc gia',
    region: 'Khu vực',
    city: 'Thành phố',
    paidHelp: 'Nguồn lương và giá công khai theo quốc gia bạn chọn. Nghề giúp tính báo giá.',
    freeHelp: 'Gói này có trợ giúp báo giá cơ bản. Pro mở nguồn theo quốc gia, khu vực và việc tương tự.',
    publicSources: 'Nguồn công khai cho quốc gia này'
  }
} as const;

export function getQuoteFieldCopy(locale: Locale) {
  return quoteFieldCopy[locale] || quoteFieldCopy.en;
}
