import type { Locale } from '@/lib/i18n/config';

export type CatchActionCopy = {
  leadTitle:(name:string)=>string; leadOldReason:string; leadNewReason:string;
  bookingTitle:(name:string)=>string; bookingReason:string;
  jobTitle:(title:string)=>string; jobReason:string;
  reviewTitle:(name:string)=>string; reviewReason:string;
  repeatTitle:(name:string)=>string; repeatReason:string;
  quoteTitle:(name:string)=>string; quoteReason:string;
  invoiceTitle:(name:string)=>string; invoiceReason:string;
  inquiryDraft:(name:string)=>string; bookingDraft:(name:string)=>string; jobDraft:(name:string)=>string;
  reviewDraft:(name:string)=>string; repeatDraft:(name:string)=>string; quoteDraft:(name:string)=>string; invoiceDraft:(name:string)=>string;
  jobValueLabel:string; quoteValueLabel:string; balanceDueLabel:string;
};
type CatchCopy={product:string;plan:string;title:string;upgrade:string;checking:string;empty:string;open:string;email:string;send:string;sending:string;sent:string;done:string;hide:string;hidden:string;showAgain:string;to:string;savedEmail:string;anotherEmail:string;emailAddress:string;subject:string;message:string;close:string;emailSubject:string;emailRequired:string;sendError:string;saveError:string;untitledJob:string;job:string;bookingRequest:string;quote:string;invoice:string;highPriority:string;standard:string;more:string;showLess:string;actions:CatchActionCopy};
function firstName(name:string,fallback:string){return name.trim().split(/\s+/)[0]||fallback;}
const COPY:Record<Locale,CatchCopy>={
 en:{product:'Follow-Up',plan:'Enterprise',title:'Needs attention',upgrade:'Upgrade to Enterprise',checking:'Checking...',empty:'Nothing needs attention.',open:'Open',email:'Email',send:'Send',sending:'Sending...',sent:'Sent',done:'Done',hide:'Hide',hidden:'Hidden',showAgain:'Show again',to:'To',savedEmail:'Saved email',anotherEmail:'Use another email',emailAddress:'Email address',subject:'Subject',message:'Message',close:'Close',emailSubject:'Checking in',emailRequired:'Enter an email address.',sendError:'Email was not sent.',saveError:'Could not save that change.',untitledJob:'Untitled job',job:'Job',bookingRequest:'Booking request',quote:'Quote',invoice:'Invoice',highPriority:'High priority',standard:'Standard',more:'More',showLess:'Show less',actions:{leadTitle:n=>`Reply to ${n}`,leadOldReason:'Waiting 3 days',leadNewReason:'Waiting 24 hours',bookingTitle:n=>`Confirm ${n}`,bookingReason:'Waiting for confirmation',jobTitle:t=>`Check ${t}`,jobReason:'Job still open',reviewTitle:n=>`Ask ${n} for a review`,reviewReason:'Job finished 3 days ago',repeatTitle:n=>`Check if ${n} needs repeat service`,repeatReason:'No activity for 60 days',quoteTitle:n=>`Follow up on ${n}'s quote`,quoteReason:'Quote sent 2 days ago',invoiceTitle:n=>`Remind ${n} about payment`,invoiceReason:'Invoice is unpaid',inquiryDraft:n=>`Hi ${firstName(n,'there')}, just following up on your request. Are you still looking to get this scheduled?`,bookingDraft:n=>`Hi ${firstName(n,'there')}, just checking that the scheduled time still works for you.`,jobDraft:n=>`Hi ${firstName(n,'there')}, just checking in. Is there anything you need from us?`,reviewDraft:n=>`Hi ${firstName(n,'there')}, thanks again for choosing us. If you were happy with the work, we would really appreciate a review.`,repeatDraft:n=>`Hi ${firstName(n,'there')}, it has been a while since we worked together. Do you need us to schedule another service?`,quoteDraft:n=>`Hi ${firstName(n,'there')}, just checking in on the quote we sent. Do you have any questions or would you like to move forward?`,invoiceDraft:n=>`Hi ${firstName(n,'there')}, just a reminder that there is still a balance due on your invoice. Please let us know if you have any questions.`,jobValueLabel:'Job value',quoteValueLabel:'Quote value',balanceDueLabel:'Balance due'}},
 es:{product:'Seguimiento',plan:'Enterprise',title:'Necesita atención',upgrade:'Cambiar a Enterprise',checking:'Revisando...',empty:'Nada necesita atención.',open:'Abrir',email:'Correo',send:'Enviar',sending:'Enviando...',sent:'Enviado',done:'Listo',hide:'Ocultar',hidden:'Ocultos',showAgain:'Mostrar de nuevo',to:'Para',savedEmail:'Correo guardado',anotherEmail:'Usar otro correo',emailAddress:'Correo electrónico',subject:'Asunto',message:'Mensaje',close:'Cerrar',emailSubject:'Seguimiento',emailRequired:'Ingresa un correo electrónico.',sendError:'No se envió el correo.',saveError:'No se pudo guardar el cambio.',untitledJob:'Trabajo sin título',job:'Trabajo',bookingRequest:'Solicitud de reserva',quote:'Cotización',invoice:'Factura',highPriority:'Alta prioridad',standard:'Normal',more:'Más',showLess:'Ver menos',actions:{leadTitle:n=>`Responder a ${n}`,leadOldReason:'Esperando 3 días',leadNewReason:'Esperando 24 horas',bookingTitle:n=>`Confirmar con ${n}`,bookingReason:'Falta confirmación',jobTitle:t=>`Revisar ${t}`,jobReason:'El trabajo sigue abierto',reviewTitle:n=>`Pedir una reseña a ${n}`,reviewReason:'El trabajo terminó hace 3 días',repeatTitle:n=>`Ver si ${n} necesita otro servicio`,repeatReason:'Sin actividad por 60 días',quoteTitle:n=>`Dar seguimiento a la cotización de ${n}`,quoteReason:'Cotización enviada hace 2 días',invoiceTitle:n=>`Recordar el pago a ${n}`,invoiceReason:'La factura sigue pendiente',inquiryDraft:n=>`Hola ${firstName(n,'de nuevo')}, quería saber si todavía quieres programar el servicio.`,bookingDraft:n=>`Hola ${firstName(n,'de nuevo')}, quería confirmar que la hora programada todavía te funciona.`,jobDraft:n=>`Hola ${firstName(n,'de nuevo')}, quería saber cómo va todo. ¿Necesitas algo de nosotros?`,reviewDraft:n=>`Hola ${firstName(n,'de nuevo')}, gracias otra vez por elegirnos. Si quedaste satisfecho con el trabajo, agradeceríamos mucho una reseña.`,repeatDraft:n=>`Hola ${firstName(n,'de nuevo')}, ha pasado tiempo desde que trabajamos juntos. ¿Quieres programar otro servicio?`,quoteDraft:n=>`Hola ${firstName(n,'de nuevo')}, quería dar seguimiento a la cotización que enviamos. ¿Tienes alguna pregunta o quieres seguir adelante?`,invoiceDraft:n=>`Hola ${firstName(n,'de nuevo')}, este es un recordatorio de que todavía hay un saldo pendiente en tu factura. Avísanos si tienes alguna pregunta.`,jobValueLabel:'Valor del trabajo',quoteValueLabel:'Valor de la cotización',balanceDueLabel:'Saldo pendiente'}},
 vi:{product:'Theo dõi',plan:'Enterprise',title:'Cần xử lý',upgrade:'Nâng cấp Enterprise',checking:'Đang kiểm tra...',empty:'Không có việc cần xử lý.',open:'Mở',email:'Email',send:'Gửi',sending:'Đang gửi...',sent:'Đã gửi',done:'Xong',hide:'Ẩn',hidden:'Đã ẩn',showAgain:'Hiện lại',to:'Đến',savedEmail:'Email đã lưu',anotherEmail:'Dùng email khác',emailAddress:'Địa chỉ email',subject:'Tiêu đề',message:'Nội dung',close:'Đóng',emailSubject:'Hỏi thăm',emailRequired:'Nhập địa chỉ email.',sendError:'Không gửi được email.',saveError:'Không lưu được thay đổi.',untitledJob:'Công việc chưa đặt tên',job:'Công việc',bookingRequest:'Yêu cầu đặt lịch',quote:'Báo giá',invoice:'Hóa đơn',highPriority:'Ưu tiên cao',standard:'Thông thường',more:'Xem thêm',showLess:'Thu gọn',actions:{leadTitle:n=>`Trả lời ${n}`,leadOldReason:'Đã chờ 3 ngày',leadNewReason:'Đã chờ 24 giờ',bookingTitle:n=>`Xác nhận với ${n}`,bookingReason:'Đang chờ xác nhận',jobTitle:t=>`Kiểm tra ${t}`,jobReason:'Công việc vẫn đang mở',reviewTitle:n=>`Xin đánh giá từ ${n}`,reviewReason:'Công việc đã xong 3 ngày',repeatTitle:n=>`Hỏi ${n} có cần làm lại dịch vụ không`,repeatReason:'Không có hoạt động trong 60 ngày',quoteTitle:n=>`Theo dõi báo giá của ${n}`,quoteReason:'Báo giá đã gửi 2 ngày',invoiceTitle:n=>`Nhắc ${n} thanh toán`,invoiceReason:'Hóa đơn chưa thanh toán',inquiryDraft:n=>`Chào ${firstName(n,'bạn')}, mình hỏi lại xem bạn vẫn muốn đặt lịch chứ?`,bookingDraft:n=>`Chào ${firstName(n,'bạn')}, mình muốn xác nhận giờ đã đặt vẫn phù hợp với bạn chứ?`,jobDraft:n=>`Chào ${firstName(n,'bạn')}, mình hỏi thăm xem mọi việc thế nào. Bạn có cần bên mình hỗ trợ gì không?`,reviewDraft:n=>`Chào ${firstName(n,'bạn')}, cảm ơn bạn đã sử dụng dịch vụ. Nếu bạn hài lòng, bên mình rất cảm kích nếu bạn để lại đánh giá.`,repeatDraft:n=>`Chào ${firstName(n,'bạn')}, đã một thời gian từ lần mình làm việc cùng nhau. Bạn có muốn đặt thêm một lần dịch vụ không?`,quoteDraft:n=>`Chào ${firstName(n,'bạn')}, mình hỏi lại về báo giá đã gửi. Bạn có câu hỏi gì hoặc muốn tiếp tục không?`,invoiceDraft:n=>`Chào ${firstName(n,'bạn')}, mình nhắc nhẹ là hóa đơn vẫn còn số tiền chưa thanh toán. Nếu bạn có câu hỏi thì cho bên mình biết nhé.`,jobValueLabel:'Giá trị công việc',quoteValueLabel:'Giá trị báo giá',balanceDueLabel:'Số tiền còn lại'}}
};
export function getCatchCopy(locale:Locale):CatchCopy{return COPY[locale]||COPY.en;}
