import type { Locale } from '@/lib/i18n/config';

export type CatchActionCopy = {
  leadTitle:(name:string)=>string; leadOldReason:string; leadNewReason:string;
  bookingTitle:(name:string)=>string; bookingReason:string;
  jobTitle:(title:string)=>string; jobReason:string;
  followUpTitle:(title:string,name:string)=>string; followUpReason:string;
  returnTitle:(name:string)=>string; returnReason:string;
  inquiryDraft:(name:string)=>string; bookingDraft:(name:string)=>string; jobDraft:(name:string)=>string; followUpDraft:(name:string,title?:string,highValue?:boolean)=>string; returnDraft:(name:string)=>string;
};
type CatchCopy={product:string;plan:string;title:string;upgrade:string;checking:string;empty:string;open:string;email:string;send:string;sending:string;sent:string;done:string;hide:string;hidden:string;showAgain:string;to:string;savedEmail:string;anotherEmail:string;emailAddress:string;subject:string;message:string;close:string;emailSubject:string;emailRequired:string;sendError:string;saveError:string;untitledJob:string;job:string;bookingRequest:string;highPriority:string;standard:string;more:string;showLess:string;value:string;actions:CatchActionCopy};
function firstName(name:string,fallback:string){return name.trim().split(/\s+/)[0]||fallback;}
const COPY:Record<Locale,CatchCopy>={
 en:{product:'Follow-Up',plan:'Enterprise',title:'Needs attention',upgrade:'Upgrade to Enterprise',checking:'Checking...',empty:'Nothing needs attention.',open:'Open',email:'Email',send:'Send',sending:'Sending...',sent:'Sent',done:'Done',hide:'Hide',hidden:'Hidden',showAgain:'Show again',to:'To',savedEmail:'Saved email',anotherEmail:'Use another email',emailAddress:'Email address',subject:'Subject',message:'Message',close:'Close',emailSubject:'Checking in',emailRequired:'Enter an email address.',sendError:'Email was not sent.',saveError:'Could not save that change.',untitledJob:'Untitled job',job:'Job',bookingRequest:'Booking request',highPriority:'High priority',standard:'Standard',more:'More',showLess:'Show less',value:'Job value',actions:{leadTitle:n=>`Reply to ${n}`,leadOldReason:'Waiting 3 days',leadNewReason:'Waiting 24 hours',bookingTitle:n=>`Confirm ${n}`,bookingReason:'Waiting for confirmation',jobTitle:t=>`Check ${t}`,jobReason:'Job still open',followUpTitle:(t,n)=>`Follow up with ${n}`,followUpReason:'Job finished 3 days ago',returnTitle:n=>`Check in with ${n}`,returnReason:'No activity for 60 days',inquiryDraft:n=>`Hi ${firstName(n,'there')}, just following up on your request. Are you still looking to get this scheduled?`,bookingDraft:n=>`Hi ${firstName(n,'there')}, just checking that the scheduled time still works for you.`,jobDraft:n=>`Hi ${firstName(n,'there')}, just checking in. Is there anything you need from us?`,followUpDraft:(n)=>`Hi ${firstName(n,'there')}, just checking in after your recent service. How did everything go? If you were happy with the work, we'd really appreciate a review.`,returnDraft:n=>`Hi ${firstName(n,'there')}, it has been a while since we worked together. Is there anything we can help you with?`}},
 es:{product:'Seguimiento',plan:'Enterprise',title:'Necesita atención',upgrade:'Cambiar a Enterprise',checking:'Revisando...',empty:'Nada necesita atención.',open:'Abrir',email:'Correo',send:'Enviar',sending:'Enviando...',sent:'Enviado',done:'Listo',hide:'Ocultar',hidden:'Ocultos',showAgain:'Mostrar de nuevo',to:'Para',savedEmail:'Correo guardado',anotherEmail:'Usar otro correo',emailAddress:'Correo electrónico',subject:'Asunto',message:'Mensaje',close:'Cerrar',emailSubject:'Seguimiento',emailRequired:'Ingresa un correo electrónico.',sendError:'No se envió el correo.',saveError:'No se pudo guardar el cambio.',untitledJob:'Trabajo sin título',job:'Trabajo',bookingRequest:'Solicitud de reserva',highPriority:'Alta prioridad',standard:'Normal',more:'Más',showLess:'Ver menos',value:'Valor del trabajo',actions:{leadTitle:n=>`Responder a ${n}`,leadOldReason:'Esperando 3 días',leadNewReason:'Esperando 24 horas',bookingTitle:n=>`Confirmar con ${n}`,bookingReason:'Falta confirmación',jobTitle:t=>`Revisar ${t}`,jobReason:'El trabajo sigue abierto',followUpTitle:(t,n)=>`Dar seguimiento con ${n}`,followUpReason:'El trabajo terminó hace 3 días',returnTitle:n=>`Contactar a ${n}`,returnReason:'Sin actividad por 60 días',inquiryDraft:n=>`Hola ${firstName(n,'de nuevo')}, quería saber si todavía quieres programar el servicio.`,bookingDraft:n=>`Hola ${firstName(n,'de nuevo')}, quería confirmar que la hora programada todavía te funciona.`,jobDraft:n=>`Hola ${firstName(n,'de nuevo')}, quería saber cómo va todo. ¿Necesitas algo de nosotros?`,followUpDraft:n=>`Hola ${firstName(n,'de nuevo')}, quería saber cómo salió todo con tu servicio reciente. Si quedaste satisfecho con el trabajo, agradeceríamos mucho una reseña.`,returnDraft:n=>`Hola ${firstName(n,'de nuevo')}, ha pasado tiempo desde que trabajamos juntos. ¿Hay algo en lo que podamos ayudarte?`}},
 vi:{product:'Theo dõi',plan:'Enterprise',title:'Cần xử lý',upgrade:'Nâng cấp Enterprise',checking:'Đang kiểm tra...',empty:'Không có việc cần xử lý.',open:'Mở',email:'Email',send:'Gửi',sending:'Đang gửi...',sent:'Đã gửi',done:'Xong',hide:'Ẩn',hidden:'Đã ẩn',showAgain:'Hiện lại',to:'Đến',savedEmail:'Email đã lưu',anotherEmail:'Dùng email khác',emailAddress:'Địa chỉ email',subject:'Tiêu đề',message:'Nội dung',close:'Đóng',emailSubject:'Hỏi thăm',emailRequired:'Nhập địa chỉ email.',sendError:'Không gửi được email.',saveError:'Không lưu được thay đổi.',untitledJob:'Công việc chưa đặt tên',job:'Công việc',bookingRequest:'Yêu cầu đặt lịch',highPriority:'Ưu tiên cao',standard:'Thông thường',more:'Xem thêm',showLess:'Thu gọn',value:'Giá trị công việc',actions:{leadTitle:n=>`Trả lời ${n}`,leadOldReason:'Đã chờ 3 ngày',leadNewReason:'Đã chờ 24 giờ',bookingTitle:n=>`Xác nhận với ${n}`,bookingReason:'Đang chờ xác nhận',jobTitle:t=>`Kiểm tra ${t}`,jobReason:'Công việc vẫn đang mở',followUpTitle:(t,n)=>`Hỏi thăm ${n}`,followUpReason:'Công việc đã xong 3 ngày',returnTitle:n=>`Liên hệ lại ${n}`,returnReason:'Không có hoạt động trong 60 ngày',inquiryDraft:n=>`Chào ${firstName(n,'bạn')}, mình hỏi lại xem bạn vẫn muốn đặt lịch chứ?`,bookingDraft:n=>`Chào ${firstName(n,'bạn')}, mình muốn xác nhận giờ đã đặt vẫn phù hợp với bạn chứ?`,jobDraft:n=>`Chào ${firstName(n,'bạn')}, mình hỏi thăm xem mọi việc thế nào. Bạn có cần bên mình hỗ trợ gì không?`,followUpDraft:n=>`Chào ${firstName(n,'bạn')}, mình hỏi thăm về dịch vụ vừa rồi. Mọi việc ổn chứ? Nếu bạn hài lòng với công việc, bên mình rất cảm kích nếu bạn để lại đánh giá.`,returnDraft:n=>`Chào ${firstName(n,'bạn')}, đã một thời gian từ lần mình làm việc cùng nhau. Bạn có việc gì cần bên mình hỗ trợ không?`}}
};
export function getCatchCopy(locale:Locale):CatchCopy{return COPY[locale]||COPY.en;}
