import { normalizeLocale, type Locale } from '@/lib/i18n/config';
import type { DashboardDateRange } from '@/lib/dashboard-metrics';
import type { DashboardDetailMetric } from '@/lib/dashboard-metric-details';

export type DashboardFinanceCopy = {
  ranges: Partial<Record<DashboardDateRange, string>>;
  metricTitles: Record<DashboardDetailMetric, string>;
  formulas: Record<DashboardDetailMetric, string>;
  details: { titleFallback: string; subtitle: string; exactTotal: string; empty: string; tryAgain: string; unknownMetric: string; loadError: string; loading: string };
  overview: { title: string; subtitle: string; periodLabel: string; moneySummaryTitle: string; moreDetails: string; hideDetails: string; loadError: string; missingCompletedAtWarning: string; fixJob: string };
  money: Record<string, string>;
  contractorPayPage: Record<string, string>;
};

const ranges = {
  en: { today: 'Today', week: 'This week', month: 'This month', quarter: 'This quarter', ytd: 'YTD', year: 'This year', last_year: 'Last year', all_time: 'All time' },
  es: { today: 'Hoy', week: 'Esta semana', month: 'Este mes', quarter: 'Este trimestre', ytd: 'Año hasta hoy', year: 'Este año', last_year: 'El año pasado', all_time: 'Todo el tiempo' },
  vi: { today: 'Hôm nay', week: 'Tuần này', month: 'Tháng này', quarter: 'Quý này', ytd: 'Từ đầu năm đến nay', year: 'Năm nay', last_year: 'Năm trước', all_time: 'Toàn thời gian' }
} satisfies Record<Locale, Partial<Record<DashboardDateRange, string>>>;

const metricTitles: Record<DashboardDetailMetric, string> = { collected: 'Collected', invoiced: 'Invoiced', outstanding: 'Outstanding', late: 'Late payments', 'unpaid-invoices': 'Unpaid invoices', 'net-cash': 'Cash after paid costs', 'estimated-profit': 'Expected profit', 'contractor-pay': 'Worker cost', 'contractor-pay-owed': 'Worker pay owed', 'contractor-pay-pending': 'Worker pay pending', expenses: 'Expenses', 'completed-jobs': 'Completed jobs', jobs: 'Jobs', 'active-customers': 'Active customers' };
const formulas: Record<DashboardDetailMetric, string> = { collected: 'Money received = invoice payments + direct job payments in the selected period. The same payment is never counted twice.', invoiced: 'Invoiced = collectible invoice totals created in the selected period.', outstanding: 'Customers owe = remaining unpaid invoice balances plus unpaid direct jobs without invoices.', late: 'Late = unpaid invoice balances past their due date.', 'unpaid-invoices': 'Unpaid invoices = invoices with a remaining balance.', 'net-cash': 'Money kept = money received minus paid workers minus business expenses.', 'estimated-profit': 'Profit = job revenue minus worker costs minus business expenses. Job revenue = money received + customers owe.', 'contractor-pay': 'Worker costs = labor totals for jobs in the selected period.', 'contractor-pay-owed': 'Worker pay owed = labor still marked unpaid.', 'contractor-pay-pending': 'Worker pay pending = labor marked pending.', expenses: 'Business expenses = expense amounts with dates in the selected period.', 'completed-jobs': 'Completed jobs counted by completion date or operational date fallback.', jobs: 'Jobs counted by operational work date in the selected period.', 'active-customers': 'Active customers = current customer records.' };
const details = { titleFallback: 'Metric details', subtitle: 'See the records behind each dashboard total.', exactTotal: 'Exact total', empty: 'No records in this period.', tryAgain: 'Try again', unknownMetric: 'Unknown dashboard metric.', loadError: 'Unable to load metric details.', loading: 'Loading…' };
const overview = { title: 'Business overview', subtitle: 'Period metrics for the selected range.', periodLabel: 'Dashboard period', moneySummaryTitle: 'Money summary', moreDetails: 'More details', hideDetails: 'Hide details', loadError: 'Some financial totals could not be loaded. Refresh and try again.', missingCompletedAtWarning: '{count} completed jobs are missing completion dates', fixJob: 'Fix job' };
const money = { expectedRevenue: 'Job revenue', expectedRevenueHelp: 'Money received plus money customers still owe for the selected period.', collected: 'Money received', collectedHelp: 'Customer payments actually received in this period.', outstanding: 'Customers owe', outstandingHelp: 'Remaining unpaid balances for the selected period.', invoiced: 'Invoiced', invoicedHelp: 'Invoice totals in this period.', netCash: 'Money kept', netCashHelp: 'Money received minus paid workers minus business expenses.', latePayments: 'Late payments', latePaymentsHelp: 'Current overdue unpaid balances.', lateInvoices: 'Late invoices', unpaidInvoices: 'Unpaid invoices', unpaidInvoicesHelp: 'Invoices with a remaining balance.', averageDays: 'Average time to get paid', averageDaysNone: 'No fully paid invoices yet', averageDaysHelp: 'Average days to recorded payment.', averageDaysHelpEmpty: 'Appears after a fully paid invoice has payment dates.', contractorCost: 'Worker costs', contractorCostHelp: 'Labor cost for jobs in this period.', contractorPay: 'Worker costs', contractorPayHelp: 'Labor cost for jobs in this period.', contractorPayOwed: 'Worker pay owed', contractorPayOwedHelp: 'Unpaid worker labor in this period.', contractorPayPending: 'Worker pay pending', contractorPayPendingHelp: 'Worker pay marked pending.', contractorPayPaid: 'Paid workers', contractorPayPaidHelp: 'Worker payments paid in this period.', otherExpenses: 'Business expenses', otherExpensesHelp: 'Business expenses dated in this period.', expectedProfit: 'Profit', expectedProfitHelp: 'Job revenue minus worker costs and business expenses.', cashAfterCosts: 'Money kept', cashAfterCostsHelp: 'Money received minus paid workers and business expenses.', expectedProfitPct: 'Profit percentage', expectedProfitPctHelp: 'Profit divided by job revenue.', costsMissing: 'Only recorded costs are included.', uninvoicedWork: 'Uninvoiced expected revenue', uninvoicedWorkHelp: 'Expected job revenue not yet invoiced.', paymentsMissingDates: 'Payments missing dates', paymentsMissingDatesHelp: 'Add payment dates for accurate period totals.', completedJobs: 'Completed jobs', completedJobsHelp: 'Jobs completed in the selected period.', jobs: 'Jobs', jobsHelp: 'Jobs in the selected period.', activeCustomers: 'Active customers', activeCustomersHelp: 'Current active customers.', bookings: 'Bookings', messages: 'Messages', reports: 'Reports', current: 'Current', days: 'days' };
const contractorPayPage = { title: 'Team Pay', subtitle: 'Review worker and employee payments linked to jobs.', privacyNotice: 'Private company financial information.', permissionDenied: 'You do not have access to team pay.', stillOwed: 'Still owed', pending: 'Pending', paid: 'Paid', allPayments: 'All team payments', statusPayments: '{status} team payments', changesHint: 'Changes here update dashboard totals.', showAll: 'Show all', refresh: 'Refresh', refreshing: 'Refreshing…', loading: 'Loading team payments…', empty: 'No team payments match this status.', openJob: 'Open job', markPending: 'Mark pending', markPaid: 'Mark paid', updateError: 'Unable to update team payment.', markedPaid: 'Team payment marked paid.', markedStatus: 'Team payment marked {status}.', unnamed: 'Unassigned worker', jobFallback: 'Job', contractorOrCleaner: 'Team member', contractorNamePlaceholder: 'Team member name', paymentMethodLabel: 'Payment method', reviewPayment: 'Review payment', addAnotherPayment: 'Add another payment', flatRate: 'Flat rate', hourly: 'Hourly', amount: 'Amount', hours: 'Hours', hourlyRate: 'Hourly rate', calculatedTotal: 'Calculated total', notesOptional: 'Notes (optional)', initializeFromJob: 'Payment details were filled from this job.', added: 'Team payment added.', updated: 'Team payment updated.', removed: 'Team payment removed.', duplicated: 'Team payment duplicated.' };

const base = (locale: Locale): DashboardFinanceCopy => ({ ranges: ranges[locale], metricTitles, formulas, details, overview, money, contractorPayPage });
const byLocale: Record<Locale, DashboardFinanceCopy> = { en: base('en'), es: base('es'), vi: base('vi') };
export function getDashboardFinanceCopy(locale: string | null | undefined): DashboardFinanceCopy { return byLocale[normalizeLocale(locale)]; }
export function formatDashboardCopy(template: string, values?: Record<string, string | number>): string { if (!values) return template; return Object.entries(values).reduce((result, [key, value]) => result.replace(new RegExp(`\\{${key}\\}`, 'g'), String(value)), template); }
