import type { Locale } from '@/lib/i18n/config';

export const OPS_COPY = {
  templates: {
    en: { title:'Template Library', subtitle:'SOPs, proposals, contracts, emails, and checklists for your organization.', loadError:'Unable to load templates', schema:'Template tables are not set up yet. Run supabase/manual_schema_repair.sql in the Supabase SQL Editor, then refresh.', categoryFilter:'Category filter', all:'All', newTemplate:'New template', editTemplate:'Edit template', titleField:'Title', body:'Template body', update:'Update', create:'Create', cancel:'Cancel', loading:'Loading…', edit:'Edit', duplicate:'Duplicate', delete:'Delete', deleteConfirm:'Delete this template?' },
    es: { title:'Biblioteca de plantillas', subtitle:'Procedimientos, propuestas, contratos, correos y listas para tu organización.', loadError:'No se pudieron cargar las plantillas', schema:'Las tablas de plantillas aún no están configuradas. Ejecuta supabase/manual_schema_repair.sql en el Editor SQL de Supabase y actualiza la página.', categoryFilter:'Filtro de categoría', all:'Todas', newTemplate:'Nueva plantilla', editTemplate:'Editar plantilla', titleField:'Título', body:'Contenido de la plantilla', update:'Actualizar', create:'Crear', cancel:'Cancelar', loading:'Cargando…', edit:'Editar', duplicate:'Duplicar', delete:'Eliminar', deleteConfirm:'¿Eliminar esta plantilla?' },
    vi: { title:'Thư viện mẫu', subtitle:'Quy trình, đề xuất, hợp đồng, email và danh sách kiểm tra cho tổ chức của bạn.', loadError:'Không thể tải mẫu', schema:'Bảng mẫu chưa được thiết lập. Chạy supabase/manual_schema_repair.sql trong Supabase SQL Editor rồi làm mới trang.', categoryFilter:'Lọc theo danh mục', all:'Tất cả', newTemplate:'Mẫu mới', editTemplate:'Sửa mẫu', titleField:'Tiêu đề', body:'Nội dung mẫu', update:'Cập nhật', create:'Tạo', cancel:'Hủy', loading:'Đang tải…', edit:'Sửa', duplicate:'Nhân bản', delete:'Xóa', deleteConfirm:'Xóa mẫu này?' }
  },
  automations: {
    en:{title:'Automation Center',subtitle:'Trigger, condition, and action workflows for your business.',feature:'Automations',jobWorkflows:'Job workflows',name:'Automation name',create:'Create automation',loading:'Loading...',empty:'No automations yet. Start with Lead Created → Create Task.',advancedPrefix:'Advanced job workflows live under',workflows:'Workflows',advancedSuffix:'on Growth and higher.'},
    es:{title:'Centro de automatización',subtitle:'Flujos con disparadores, condiciones y acciones para tu negocio.',feature:'Automatizaciones',jobWorkflows:'Flujos de trabajos',name:'Nombre de automatización',create:'Crear automatización',loading:'Cargando...',empty:'Aún no hay automatizaciones. Empieza con Prospecto creado → Crear tarea.',advancedPrefix:'Los flujos avanzados de trabajos están en',workflows:'Flujos',advancedSuffix:'en Growth y superiores.'},
    vi:{title:'Trung tâm tự động hóa',subtitle:'Quy trình kích hoạt, điều kiện và hành động cho doanh nghiệp.',feature:'Tự động hóa',jobWorkflows:'Quy trình công việc',name:'Tên tự động hóa',create:'Tạo tự động hóa',loading:'Đang tải...',empty:'Chưa có tự động hóa. Bắt đầu với Khách tiềm năng mới → Tạo nhiệm vụ.',advancedPrefix:'Quy trình công việc nâng cao nằm trong',workflows:'Quy trình',advancedSuffix:'ở gói Growth trở lên.'}
  },
  projects: {
    en:{title:'Projects & Tasks',subtitle:'Tasks, checklists, and project work across your organization.',newTask:'New task',taskTitle:'Task title',addTask:'Add task',tasks:'Tasks',loading:'Loading...',empty:'No tasks yet. Create one above or from a job.',footerPrefix:'Board and calendar views are coming next. Jobs with checklists remain under',jobs:'Jobs'},
    es:{title:'Proyectos y tareas',subtitle:'Tareas, listas y trabajo de proyectos en toda tu organización.',newTask:'Nueva tarea',taskTitle:'Título de la tarea',addTask:'Agregar tarea',tasks:'Tareas',loading:'Cargando...',empty:'Aún no hay tareas. Crea una arriba o desde un trabajo.',footerPrefix:'Las vistas de tablero y calendario llegarán después. Los trabajos con listas siguen en',jobs:'Trabajos'},
    vi:{title:'Dự án và nhiệm vụ',subtitle:'Nhiệm vụ, danh sách kiểm tra và công việc dự án trong tổ chức.',newTask:'Nhiệm vụ mới',taskTitle:'Tên nhiệm vụ',addTask:'Thêm nhiệm vụ',tasks:'Nhiệm vụ',loading:'Đang tải...',empty:'Chưa có nhiệm vụ. Tạo một nhiệm vụ ở trên hoặc từ công việc.',footerPrefix:'Chế độ bảng và lịch sẽ có sau. Công việc có danh sách kiểm tra vẫn nằm trong',jobs:'Công việc'}
  },
  workflows: {
    en:{loading:'Loading workflows...',title:'Workflows',subtitle:'Job workflows and checklist templates for Growth and higher.',feature:'Workflows',createTitle:'Create workflow',name:'Workflow name',firstStep:'First step (optional)',create:'Create workflow',noDescription:'No description',deactivate:'Deactivate',activate:'Activate',stepTitle:'Step title',up:'Up',down:'Down',addStep:'Add step',back:'Back to settings'},
    es:{loading:'Cargando flujos...',title:'Flujos',subtitle:'Flujos de trabajo y plantillas de listas para Growth y superiores.',feature:'Flujos',createTitle:'Crear flujo',name:'Nombre del flujo',firstStep:'Primer paso (opcional)',create:'Crear flujo',noDescription:'Sin descripción',deactivate:'Desactivar',activate:'Activar',stepTitle:'Título del paso',up:'Subir',down:'Bajar',addStep:'Agregar paso',back:'Volver a configuración'},
    vi:{loading:'Đang tải quy trình...',title:'Quy trình',subtitle:'Quy trình công việc và mẫu danh sách kiểm tra cho gói Growth trở lên.',feature:'Quy trình',createTitle:'Tạo quy trình',name:'Tên quy trình',firstStep:'Bước đầu tiên (không bắt buộc)',create:'Tạo quy trình',noDescription:'Không có mô tả',deactivate:'Tắt',activate:'Bật',stepTitle:'Tên bước',up:'Lên',down:'Xuống',addStep:'Thêm bước',back:'Quay lại cài đặt'}
  }
} as const;

export function getOpsCopy<K extends keyof typeof OPS_COPY>(section: K, locale: Locale) {
  return OPS_COPY[section][locale] || OPS_COPY[section].en;
}
