import type { Locale } from '@/lib/i18n/config';

type PortalRouteCopy = {
  unauthorized:string; shortMessage:string; longMessage:string; jobNotFound:string; noCompanyEmail:string; client:string; owner:string; clientSubject:(job:string)=>string; clientSigned:(name:string,job:string,message:string)=>string; createError:string; sent:string; sendError:string; chooseRecipient:string; organizationNotFound:string; noAccess:string; customerEmailMissing:string; ownerEmailMissing:string; workerSubjectOwner:(job:string)=>string; workerSubjectCustomer:string; workerSigned:(job:string,message:string)=>string; messagingUnavailable:string; emailedCustomer:string; emailedOwner:string; emailSendError:string;
};

const COPY:Record<Locale,PortalRouteCopy>={
 en:{unauthorized:'Unauthorized',shortMessage:'Write a short message first.',longMessage:'Keep the message under 2000 characters.',jobNotFound:'Job not found.',noCompanyEmail:'No company email is on file.',client:'Client',owner:'Owner',clientSubject:job=>`Client message about ${job}`,clientSigned:(name,job,message)=>`From ${name} about ${job}:\n\n${message}`,createError:'Unable to create message.',sent:'Message sent.',sendError:'Message could not be sent.',chooseRecipient:'Choose customer or owner.',organizationNotFound:'Organization not found.',noAccess:'You do not have access to this job.',customerEmailMissing:'This job has no customer email on file. Ask the owner to add one.',ownerEmailMissing:'No owner email is on file for this workspace.',workerSubjectOwner:job=>`Update on ${job}`,workerSubjectCustomer:'Update about your job',workerSigned:(job,message)=>`From the assigned worker on ${job}:\n\n${message}`,messagingUnavailable:'Messaging is not set up yet.',emailedCustomer:'Message emailed to the customer.',emailedOwner:'Message emailed to the owner.',emailSendError:'Email could not be sent.'},
 es:{unauthorized:'No autorizado',shortMessage:'Escribe primero un mensaje corto.',longMessage:'Mantén el mensaje por debajo de 2000 caracteres.',jobNotFound:'No se encontró el trabajo.',noCompanyEmail:'No hay un correo de la empresa registrado.',client:'Cliente',owner:'Propietario',clientSubject:job=>`Mensaje del cliente sobre ${job}`,clientSigned:(name,job,message)=>`De ${name} sobre ${job}:\n\n${message}`,createError:'No se pudo crear el mensaje.',sent:'Mensaje enviado.',sendError:'No se pudo enviar el mensaje.',chooseRecipient:'Elige cliente o propietario.',organizationNotFound:'No se encontró la organización.',noAccess:'No tienes acceso a este trabajo.',customerEmailMissing:'Este trabajo no tiene correo del cliente. Pide al propietario que agregue uno.',ownerEmailMissing:'No hay correo del propietario registrado para este espacio.',workerSubjectOwner:job=>`Actualización sobre ${job}`,workerSubjectCustomer:'Actualización sobre tu trabajo',workerSigned:(job,message)=>`Del trabajador asignado en ${job}:\n\n${message}`,messagingUnavailable:'La mensajería aún no está configurada.',emailedCustomer:'Mensaje enviado por correo al cliente.',emailedOwner:'Mensaje enviado por correo al propietario.',emailSendError:'No se pudo enviar el correo.'},
 vi:{unauthorized:'Không được phép',shortMessage:'Hãy viết một tin nhắn ngắn trước.',longMessage:'Giữ tin nhắn dưới 2000 ký tự.',jobNotFound:'Không tìm thấy công việc.',noCompanyEmail:'Chưa có email công ty trong hồ sơ.',client:'Khách hàng',owner:'Chủ sở hữu',clientSubject:job=>`Tin nhắn khách hàng về ${job}`,clientSigned:(name,job,message)=>`Từ ${name} về ${job}:\n\n${message}`,createError:'Không thể tạo tin nhắn.',sent:'Đã gửi tin nhắn.',sendError:'Không thể gửi tin nhắn.',chooseRecipient:'Chọn khách hàng hoặc chủ sở hữu.',organizationNotFound:'Không tìm thấy tổ chức.',noAccess:'Bạn không có quyền truy cập công việc này.',customerEmailMissing:'Công việc này chưa có email khách hàng. Hãy nhờ chủ sở hữu thêm email.',ownerEmailMissing:'Không có email chủ sở hữu cho không gian làm việc này.',workerSubjectOwner:job=>`Cập nhật về ${job}`,workerSubjectCustomer:'Cập nhật về công việc của bạn',workerSigned:(job,message)=>`Từ nhân viên được phân công cho ${job}:\n\n${message}`,messagingUnavailable:'Tính năng nhắn tin chưa được thiết lập.',emailedCustomer:'Đã gửi email cho khách hàng.',emailedOwner:'Đã gửi email cho chủ sở hữu.',emailSendError:'Không thể gửi email.'}
};

export function getPortalMessageRouteCopy(locale:Locale):PortalRouteCopy{return COPY[locale]||COPY.en;}
