import type { Locale } from '@/lib/i18n/config';

export const PUBLIC_BOOKING_COPY = {
  en:{notFound:'Booking page not found.',loadTimes:'Unable to load times.',completeError:'Unable to complete booking.',businessFallback:'Your business',appointment:'Appointment',bookingFor:'Booking for',loading:'Loading booking…',bookOnline:'Book an appointment online',chooseService:'Choose a service',minutes:'min',continue:'Continue',chooseStaff:'Choose staff',anyAvailable:'Any available',assignNext:'We will assign the next available team member',back:'Back',chooseDateTime:'Choose date & time',date:'Date',loadingTimes:'Loading available times…',noTimes:'No open times on this date. Try another day.',yourDetails:'Your details',fullName:'Full name *',phone:'Phone',email:'Email',notes:'Notes (optional)',confirming:'Confirming…',confirmBooking:'Confirm booking',confirmed:'Your booking request is confirmed.',addCalendar:'Add to calendar',confirmationSent:'We sent a confirmation email.'},
  es:{notFound:'No se encontró la página de reservas.',loadTimes:'No se pudieron cargar los horarios.',completeError:'No se pudo completar la reserva.',businessFallback:'Tu negocio',appointment:'Cita',bookingFor:'Reserva para',loading:'Cargando reserva…',bookOnline:'Reserva una cita en línea',chooseService:'Elige un servicio',minutes:'min',continue:'Continuar',chooseStaff:'Elige personal',anyAvailable:'Cualquiera disponible',assignNext:'Asignaremos al próximo miembro disponible del equipo',back:'Atrás',chooseDateTime:'Elige fecha y hora',date:'Fecha',loadingTimes:'Cargando horarios disponibles…',noTimes:'No hay horarios disponibles en esta fecha. Prueba otro día.',yourDetails:'Tus datos',fullName:'Nombre completo *',phone:'Teléfono',email:'Correo electrónico',notes:'Notas (opcional)',confirming:'Confirmando…',confirmBooking:'Confirmar reserva',confirmed:'Tu solicitud de reserva está confirmada.',addCalendar:'Agregar al calendario',confirmationSent:'Enviamos un correo de confirmación.'},
  vi:{notFound:'Không tìm thấy trang đặt lịch.',loadTimes:'Không thể tải khung giờ.',completeError:'Không thể hoàn tất đặt lịch.',businessFallback:'Doanh nghiệp của bạn',appointment:'Lịch hẹn',bookingFor:'Đặt lịch cho',loading:'Đang tải đặt lịch…',bookOnline:'Đặt lịch hẹn trực tuyến',chooseService:'Chọn dịch vụ',minutes:'phút',continue:'Tiếp tục',chooseStaff:'Chọn nhân viên',anyAvailable:'Bất kỳ ai còn trống',assignNext:'Chúng tôi sẽ phân công thành viên còn trống tiếp theo',back:'Quay lại',chooseDateTime:'Chọn ngày và giờ',date:'Ngày',loadingTimes:'Đang tải giờ còn trống…',noTimes:'Ngày này không còn giờ trống. Hãy thử ngày khác.',yourDetails:'Thông tin của bạn',fullName:'Họ tên *',phone:'Điện thoại',email:'Email',notes:'Ghi chú (không bắt buộc)',confirming:'Đang xác nhận…',confirmBooking:'Xác nhận đặt lịch',confirmed:'Yêu cầu đặt lịch của bạn đã được xác nhận.',addCalendar:'Thêm vào lịch',confirmationSent:'Chúng tôi đã gửi email xác nhận.'}
} as const;

export const QUOTE_PRINT_COPY = {
  en:{loadError:'Could not load quote.',loading:'Loading quote...',print:'Print / Save PDF',quote:'QUOTE',preparedFor:'Prepared for',customer:'Customer',date:'Date',service:'Service',quotedPrice:'Quoted price',details:'Details',thanks:'Thank you for the opportunity to help with your property.'},
  es:{loadError:'No se pudo cargar la cotización.',loading:'Cargando cotización...',print:'Imprimir / Guardar PDF',quote:'COTIZACIÓN',preparedFor:'Preparado para',customer:'Cliente',date:'Fecha',service:'Servicio',quotedPrice:'Precio cotizado',details:'Detalles',thanks:'Gracias por la oportunidad de ayudar con tu propiedad.'},
  vi:{loadError:'Không thể tải báo giá.',loading:'Đang tải báo giá...',print:'In / Lưu PDF',quote:'BÁO GIÁ',preparedFor:'Chuẩn bị cho',customer:'Khách hàng',date:'Ngày',service:'Dịch vụ',quotedPrice:'Giá báo',details:'Chi tiết',thanks:'Cảm ơn bạn đã cho chúng tôi cơ hội hỗ trợ với bất động sản của bạn.'}
} as const;

export function getPublicBookingCopy(locale:Locale){return PUBLIC_BOOKING_COPY[locale]||PUBLIC_BOOKING_COPY.en;}
export function getQuotePrintCopy(locale:Locale){return QUOTE_PRINT_COPY[locale]||QUOTE_PRINT_COPY.en;}
