import type { Locale } from '@/lib/i18n/config';

export type PortalMessagesCopy = {
  title:string; loading:string; client:string; business:string; writeMessage:string; sendMessage:string;
};
export type ServicesPageCopy = {
  title:string; subtitle:string; availability:string; bookings:string; addService:string; serviceName:string; category:string; description:string; durationMinutes:string; price:string; yourServices:string; loading:string; empty:string; save:string; cancel:string; inactive:string; general:string; minutes:string; edit:string; deactivate:string; activate:string; remove:string; staffAssignment:string; staffHint:string; selectStaff:string; saveStaff:string; serviceNameRequired:string; loadError:string; saveError:string; updateError:string; activated:string; deactivated:string; removeConfirm:(name:string)=>string; removeError:string; staffSaveError:string;
};

const PORTAL:Record<Locale,PortalMessagesCopy>={
 en:{title:'Client messages',loading:'Loading messages…',client:'Client',business:'Business',writeMessage:'Write a message',sendMessage:'Send message'},
 es:{title:'Mensajes del cliente',loading:'Cargando mensajes…',client:'Cliente',business:'Empresa',writeMessage:'Escribe un mensaje',sendMessage:'Enviar mensaje'},
 vi:{title:'Tin nhắn khách hàng',loading:'Đang tải tin nhắn…',client:'Khách hàng',business:'Doanh nghiệp',writeMessage:'Viết tin nhắn',sendMessage:'Gửi tin nhắn'}
};

const SERVICES:Record<Locale,ServicesPageCopy>={
 en:{title:'Services',subtitle:'Manage bookable services, staff assignments, and your public booking page.',availability:'Availability',bookings:'Bookings',addService:'Add service',serviceName:'Service name *',category:'Category',description:'Description',durationMinutes:'Duration (minutes)',price:'Price ($)',yourServices:'Your services',loading:'Loading services…',empty:'No services yet. Add your first service to start accepting bookings.',save:'Save',cancel:'Cancel',inactive:'Inactive',general:'General',minutes:'min',edit:'Edit',deactivate:'Deactivate',activate:'Activate',remove:'Remove',staffAssignment:'Staff service assignment',staffHint:'Choose a team member, tap services they can perform, then save.',selectStaff:'Select staff member',saveStaff:'Save staff services',serviceNameRequired:'Service name is required.',loadError:'Unable to load services.',saveError:'Unable to save service.',updateError:'Unable to update service.',activated:'Service activated.',deactivated:'Service deactivated.',removeConfirm:name=>`Remove service "${name}"?`,removeError:'Unable to remove service.',staffSaveError:'Unable to save staff assignment.'},
 es:{title:'Servicios',subtitle:'Administra servicios reservables, asignaciones del equipo y tu página pública de reservas.',availability:'Disponibilidad',bookings:'Reservas',addService:'Agregar servicio',serviceName:'Nombre del servicio *',category:'Categoría',description:'Descripción',durationMinutes:'Duración (minutos)',price:'Precio ($)',yourServices:'Tus servicios',loading:'Cargando servicios…',empty:'Aún no hay servicios. Agrega tu primer servicio para empezar a recibir reservas.',save:'Guardar',cancel:'Cancelar',inactive:'Inactivo',general:'General',minutes:'min',edit:'Editar',deactivate:'Desactivar',activate:'Activar',remove:'Eliminar',staffAssignment:'Asignación de servicios del personal',staffHint:'Elige un miembro del equipo, selecciona los servicios que puede realizar y guarda.',selectStaff:'Seleccionar miembro del equipo',saveStaff:'Guardar servicios del personal',serviceNameRequired:'El nombre del servicio es obligatorio.',loadError:'No se pudieron cargar los servicios.',saveError:'No se pudo guardar el servicio.',updateError:'No se pudo actualizar el servicio.',activated:'Servicio activado.',deactivated:'Servicio desactivado.',removeConfirm:name=>`¿Eliminar el servicio "${name}"?`,removeError:'No se pudo eliminar el servicio.',staffSaveError:'No se pudo guardar la asignación del personal.'},
 vi:{title:'Dịch vụ',subtitle:'Quản lý dịch vụ có thể đặt lịch, phân công nhân viên và trang đặt lịch công khai.',availability:'Lịch trống',bookings:'Lịch đặt',addService:'Thêm dịch vụ',serviceName:'Tên dịch vụ *',category:'Danh mục',description:'Mô tả',durationMinutes:'Thời lượng (phút)',price:'Giá ($)',yourServices:'Dịch vụ của bạn',loading:'Đang tải dịch vụ…',empty:'Chưa có dịch vụ. Thêm dịch vụ đầu tiên để bắt đầu nhận lịch đặt.',save:'Lưu',cancel:'Hủy',inactive:'Không hoạt động',general:'Chung',minutes:'phút',edit:'Sửa',deactivate:'Tắt',activate:'Bật',remove:'Xóa',staffAssignment:'Phân công dịch vụ cho nhân viên',staffHint:'Chọn một thành viên, chọn các dịch vụ họ có thể thực hiện rồi lưu.',selectStaff:'Chọn nhân viên',saveStaff:'Lưu dịch vụ nhân viên',serviceNameRequired:'Tên dịch vụ là bắt buộc.',loadError:'Không thể tải dịch vụ.',saveError:'Không thể lưu dịch vụ.',updateError:'Không thể cập nhật dịch vụ.',activated:'Đã bật dịch vụ.',deactivated:'Đã tắt dịch vụ.',removeConfirm:name=>`Xóa dịch vụ "${name}"?`,removeError:'Không thể xóa dịch vụ.',staffSaveError:'Không thể lưu phân công nhân viên.'}
};

export function getPortalMessagesCopy(locale:Locale){return PORTAL[locale]||PORTAL.en;}
export function getServicesPageCopy(locale:Locale){return SERVICES[locale]||SERVICES.en;}
