'use client';
import { useCallback,useEffect,useState } from 'react';
import { useRouter } from 'next/navigation';
import { AppShell } from '@/components/app-shell';
import { useLocale } from '@/components/locale-provider';
import { getTeamPageCopy } from '@/lib/i18n/team-lead-copy';
import { normalizePlan,type EverittosPlan } from '@/lib/everittos-plans';
import { isManagerRole,normalizeRole,type UserRole } from '@/lib/roles';
import { supabase } from '@/lib/supabase';
import { fetchWithTimeout,requestFailureMessage } from '@/lib/fetch-with-timeout';
type Team={id:string;name:string;description:string|null;color:string|null;active:boolean;created_at:string|null};
export default function TeamsPage(){const router=useRouter();const {locale}=useLocale();const c=getTeamPageCopy(locale);const [plan,setPlan]=useState<EverittosPlan>('free');const [role,setRole]=useState<UserRole>('owner');const [canManage,setCanManage]=useState(false);const [teams,setTeams]=useState<Team[]>([]);const [name,setName]=useState('');const [description,setDescription]=useState('');const [color,setColor]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');
const load=useCallback(async()=>{setLoading(true);setMessage('');const {data:{user}}=await supabase.auth.getUser();if(!user){router.push('/login?next=/teams');return;}const {data:profile}=await supabase.from('profiles').select('plan, role').eq('id',user.id).maybeSingle();const userRole=normalizeRole(profile?.role);setPlan(normalizePlan(profile?.plan));setRole(userRole);setCanManage(isManagerRole(userRole));const res=await fetch('/api/teams');const json=await res.json();setLoading(false);if(!res.ok){setMessage(json.error||c.loadError);return;}setTeams(json.teams||[]);},[router,c.loadError]);useEffect(()=>{void load();},[load]);
async function createTeam(){if(!name.trim()||saving)return;setSaving(true);setMessage('');try{const res=await fetchWithTimeout('/api/teams',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name.trim(),description:description.trim(),color:color.trim()})});const json=(await res.json().catch(()=>({}))) as {error?:string};if(!res.ok){setMessage(json.error||c.createError);return;}setName('');setDescription('');setColor('');setMessage(c.created);await load();}catch(error){setMessage(requestFailureMessage(error,c.createError));}finally{setSaving(false);}}
return <AppShell plan={plan} role={role}><div className="page-head"><div><h1>{c.title}</h1><p className="muted">{c.subtitle}</p></div></div>{canManage?<div className="card form" style={{marginTop:18}}><h3>{c.createTeam}</h3><input className="input" placeholder={c.teamName} value={name} onChange={e=>setName(e.target.value)}/><input className="input" placeholder={c.description} value={description} onChange={e=>setDescription(e.target.value)}/><input className="input" placeholder={c.colorOptional} value={color} onChange={e=>setColor(e.target.value)}/><button className="btn btn-primary" type="button" disabled={saving||!name.trim()} onClick={()=>void createTeam()}>{saving?c.saving:c.createTeam}</button></div>:<div className="card" style={{marginTop:18}}><p className="muted">{c.managersOnly}</p></div>}{message?<p className="auth-message" style={{marginTop:18}}>{message}</p>:null}<div className="card" style={{marginTop:18}}><h3>{c.activeTeams}</h3>{loading?<p className="loading-state">{c.loadingTeams}</p>:null}{!loading&&teams.length===0?<p className="muted">{c.noTeams}</p>:null}{teams.map(team=><div key={team.id} className="list-row"><div><strong>{team.name}</strong><p className="muted">{team.description||c.noDescription}</p><p className="muted">{team.active?c.active:c.inactive}{team.color?` · ${team.color}`:''}</p></div></div>)}</div></AppShell>;
}
