'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { JobChecklist } from '@/components/job-checklist';
import { ClientAccessPanel } from '@/components/client-access-panel';
import { JobWorkflow } from '@/components/job-workflow';
import { JobPhotosSection } from '@/components/job-photos-section';
import { JobLaborSection } from '@/components/job-labor-section';
import { JobProfitabilityCard } from '@/components/job-profitability-card';
import { JobVisitsSchedule } from '@/components/job-visits-schedule';
import { JobAssignments } from '@/components/job-assignments';
import { JobAddToCalendar } from '@/components/job-add-to-calendar';
import { RecordSharingPanel } from '@/components/record-sharing-panel';
import { AddressAutocomplete } from '@/components/address-autocomplete';
import { AppShell } from '@/components/app-shell';
import { canAccessFinancials } from '@/lib/finance-access';
import { fetchOrganizationContext } from '@/lib/organization';
import { createNotification } from '@/lib/activity';
import { StatusPill } from '@/components/status-pill';
import { canAccessFeature } from '@/lib/plan-access';
import { limitsForPlan } from '@/lib/everittos-limits';
import { normalizePlan, type EverittosPlan } from '@/lib/everittos-plans';
import { hasPermission } from '@/lib/permissions';
import { canViewInternalNotes, isContractorRole, isManagerRole, normalizeRole, type UserRole } from '@/lib/roles';
import { clientUserIdSet, isAssignableWorkerRecord } from '@/lib/filter-assignable-workers';
import { useAppFeedback } from '@/components/feedback/use-app-feedback';
import { useTranslation } from '@/components/locale-provider';
import { getBillingOpsCopy } from '@/lib/i18n/billing-ops-copy';
import { canAccessWorkspaceRecord } from '@/lib/workspace-record-access';
import { contractorIdentityFromWorkers } from '@/lib/contractor-dashboard';
import { contractorJobDetailPath } from '@/lib/contractor-job-access';
import { workerIdentityAliases } from '@/lib/worker-assignment';
import { formatSupabaseError } from '@/lib/action-messages';
import { FEEDBACK } from '@/lib/feedback-labels';
import { getJobDetailCopy } from '@/lib/i18n/job-detail-copy';
import { supabase } from '@/lib/supabase';
