'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { AppShell } from '@/components/app-shell';
import { PageHeader } from '@/components/page-header';
import { useAppFeedback } from '@/components/feedback/use-app-feedback';
import { useTranslation } from '@/components/locale-provider';
import { normalizePlan, type EverittosPlan } from '@/lib/everittos-plans';
import { isAdminRole, normalizeRole, type UserRole } from '@/lib/roles';
import { supabase } from '@/lib/supabase';
import type { BookkeepingImportDecision, BookkeepingImportRow } from '@/lib/bookkeeping-import';

const copy = {
  en: { title:'Import bookkeeping CSV', subtitle:'Upload transactions, review them first, and decide how to handle possible duplicates.', back:'Back to bookkeeping', template:'Download CSV template', upload:'Choose CSV file', paste:'Or paste CSV', preview:'Preview import', confirm:'Confirm import', working:'Working…', previewTitle:'Import preview', row:'Row', date:'Date', type:'Type', amount:'Amount', details:'Details', status:'Status', action:'Duplicate action', ok:'Ready', duplicate:'Possible duplicate', existing:'Matches an EverittOS entry with the same type, date, amount, and vendor or description.', csvDuplicate:'Matches another row in this CSV.', skip:'Skip duplicate', create:'Import anyway', import:'Import', invalid:'Needs attention', total:'rows', valid:'ready', errors:'with errors', duplicates:'possible duplicates', tooLarge:'CSV must be under 2MB.', previewError:'Could not preview the CSV.', importError:'Could not import the CSV.', done:'Import finished.', imported:'imported', skipped:'skipped', failed:'failed', invalid_type:'Type must be income, worker payment, or expense.', invalid_date:'Date is missing or invalid.', invalid_amount:'Amount must be greater than 0.' },
  es: { title:'Importar CSV de registros financieros', subtitle:'Sube transacciones, revísalas primero y decide cómo tratar posibles duplicados.', back:'Volver a registros financieros', template:'Descargar plantilla CSV', upload:'Elegir archivo CSV', paste:'O pegar CSV', preview:'Vista previa', confirm:'Confirmar importación', working:'Procesando…', previewTitle:'Vista previa de importación', row:'Fila', date:'Fecha', type:'Tipo', amount:'Monto', details:'Detalles', status:'Estado', action:'Acción para duplicados', ok:'Listo', duplicate:'Posible duplicado', existing:'Coincide con una entrada de EverittOS con el mismo tipo, fecha, monto y proveedor o descripción.', csvDuplicate:'Coincide con otra fila de este CSV.', skip:'Omitir duplicado', create:'Importar de todos modos', import:'Importar', invalid:'Requiere atención', total:'filas', valid:'listas', errors:'con errores', duplicates:'posibles duplicados', tooLarge:'El CSV debe ser menor de 2 MB.', previewError:'No se pudo revisar el CSV.', importError:'No se pudo importar el CSV.', done:'Importación terminada.', imported:'importadas', skipped:'omitidas', failed:'fallidas', invalid_type:'El tipo debe ser ingreso, pago a trabajador o gasto.', invalid_date:'La fecha falta o no es válida.', invalid_amount:'El monto debe ser mayor que 0.' },
  vi: { title:'Nhập CSV sổ thu chi', subtitle:'Tải giao dịch lên, xem trước và chọn cách xử lý các mục có thể bị trùng.', back:'Quay lại sổ thu chi', template:'Tải mẫu CSV', upload:'Chọn tệp CSV', paste:'Hoặc dán CSV', preview:'Xem trước', confirm:'Xác nhận nhập', working:'Đang xử lý…', previewTitle:'Xem trước dữ liệu nhập', row:'Dòng', date:'Ngày', type:'Loại', amount:'Số tiền', details:'Chi tiết', status:'Trạng thái', action:'Xử lý mục trùng', ok:'Sẵn sàng', duplicate:'Có thể bị trùng', existing:'Trùng với một mục EverittOS có cùng loại, ngày, số tiền và nhà cung cấp hoặc mô tả.', csvDuplicate:'Trùng với một dòng khác trong tệp CSV này.', skip:'Bỏ qua mục trùng', create:'Vẫn nhập', import:'Nhập', invalid:'Cần kiểm tra', total:'dòng', valid:'sẵn sàng', errors:'có lỗi', duplicates:'có thể bị trùng', tooLarge:'Tệp CSV phải nhỏ hơn 2 MB.', previewError:'Không thể xem trước CSV.', importError:'Không thể nhập CSV.', done:'Đã nhập xong.', imported:'đã nhập', skipped:'đã bỏ qua', failed:'thất bại', invalid_type:'Loại phải là thu nhập, thanh toán nhân sự hoặc chi phí.', invalid_date:'Ngày bị thiếu hoặc không hợp lệ.', invalid_amount:'Số tiền phải lớn hơn 0.' }
} as const;

type Summary = { total:number; valid:number; invalid:number; duplicates:number };

export default function BookkeepingImportPage() {
  const router = useRouter();
  const { locale } = useTranslation();
  const c = copy[locale];
  const appFeedback = useAppFeedback();
  const [plan,setPlan] = useState<EverittosPlan>('free');
  const [role,setRole] = useState<UserRole>('owner');
  const [csv,setCsv] = useState('');
  const [rows,setRows] = useState<BookkeepingImportRow[]>([]);
  const [summary,setSummary] = useState<Summary|null>(null);
  const [decisions,setDecisions] = useState<Record<string,BookkeepingImportDecision>>({});
  const [loading,setLoading] = useState(false);
  const [result,setResult] = useState('');

  useEffect(()=>{void (async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login?next=/bookkeeping/import');return}const {data:profile}=await supabase.from('profiles').select('plan, role').eq('id',user.id).maybeSingle();const nextRole=normalizeRole(profile?.role);setPlan(normalizePlan(profile?.plan));setRole(nextRole);if(!isAdminRole(nextRole))router.replace('/bookkeeping')})()},[router]);

  const errorLabel=(code:string)=>c[code as keyof typeof c] || code;
  async function preview(){setLoading(true);setResult('');const res=await fetch('/api/bookkeeping/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csv,preview:true})});const json=await res.json().catch(()=>({}));setLoading(false);if(!res.ok){appFeedback.error(errorLabel(String(json.error||'previewError')));return}setRows(json.rows||[]);setSummary(json.summary||null);const next:Record<string,BookkeepingImportDecision>={};for(const row of json.rows||[])if(row.duplicateKind)next[String(row.rowNumber)]='skip';setDecisions(next)}
  async function commit(){setLoading(true);const res=await fetch('/api/bookkeeping/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csv,preview:false,decisions})});const json=await res.json().catch(()=>({}));setLoading(false);if(!res.ok){appFeedback.error(c.importError);return}const text=`${c.done} ${json.summary?.imported||0} ${c.imported}, ${json.summary?.skipped||0} ${c.skipped}, ${json.summary?.failed||0} ${c.failed}.`;setResult(text);appFeedback.success(text)}

  return <AppShell plan={plan} role={role}><main className="bookkeeping-page"><PageHeader title={c.title} subtitle={c.subtitle} action={<Link className="btn" href="/bookkeeping">{c.back}</Link>} /><section className="card" style={{marginTop:16,padding:18}}><div className="button-row" style={{marginBottom:12}}><button type="button" className="btn" onClick={()=>{window.location.href='/api/bookkeeping/import'}}>{c.template}</button></div><label>{c.upload}<input className="input" type="file" accept=".csv,text/csv" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>2_000_000){appFeedback.error(c.tooLarge);return}setCsv(await file.text())}} /></label><label style={{display:'block',marginTop:12}}>{c.paste}<textarea className="input" rows={9} value={csv} onChange={e=>setCsv(e.target.value)} placeholder="type,date,amount,name,counterparty,category,payment_method,notes" /></label><div className="button-row" style={{marginTop:12}}><button type="button" className="btn btn-primary" disabled={loading||!csv.trim()} onClick={()=>void preview()}>{loading?c.working:c.preview}</button>{rows.length?<button type="button" className="btn" disabled={loading} onClick={()=>void commit()}>{c.confirm}</button>:null}</div>{summary?<p className="muted">{summary.total} {c.total} · {summary.valid} {c.valid} · {summary.invalid} {c.errors} · {summary.duplicates} {c.duplicates}</p>:null}{result?<p>{result}</p>:null}</section>{rows.length?<section className="card" style={{marginTop:16,padding:18}}><h2>{c.previewTitle}</h2><div style={{overflowX:'auto'}}><table className="table" style={{width:'100%'}}><thead><tr><th>{c.row}</th><th>{c.date}</th><th>{c.type}</th><th>{c.amount}</th><th>{c.details}</th><th>{c.status}</th><th>{c.action}</th></tr></thead><tbody>{rows.map(row=><tr key={row.rowNumber} style={row.duplicateKind?{background:'var(--selected, #EAF2FF)'}:undefined}><td>{row.rowNumber}</td><td>{row.entryDate||'—'}</td><td>{row.entryType||'—'}</td><td>{row.amount??'—'}</td><td><strong>{row.title||row.counterparty||'—'}</strong><div className="muted">{[row.counterparty,row.category,row.paymentMethod].filter(Boolean).join(' · ')}</div></td><td>{row.errors.length?<><strong>{c.invalid}</strong><div className="muted">{row.errors.map(errorLabel).join(' ')}</div></>:row.duplicateKind?<><strong>{c.duplicate}</strong><div className="muted">{row.duplicateKind==='everittos'?c.existing:c.csvDuplicate}</div></>:c.ok}</td><td>{row.duplicateKind?<select className="input" value={decisions[String(row.rowNumber)]||'skip'} onChange={e=>setDecisions(current=>({...current,[String(row.rowNumber)]:e.target.value as BookkeepingImportDecision}))}><option value="skip">{c.skip}</option><option value="create">{c.create}</option></select>:c.import}</td></tr>)}</tbody></table></div></section>:null}</main></AppShell>;
}
